// GENERATED by Tools/GenerateEmojiCatalog.swift — do not edit by hand.
// Sources (verified by SHA-256; see docs/assets.md):
//   emoji-datasource 6.1.1 emoji.json (MIT) 6e7ebffed46cc813a7e47191eaabe9c4efb39e66b731d72e21e3e8134eb8296e
//   Mattermost v11.11.1 server/public/model/emoji_data.go (Apache-2.0) f643f1a2edcadb04b980cd4b987c75362efde54caab2ccbf32a9048d6c8f2b4c
// 1810 emoji, 1490 skin-tone variants, 4463 short names.
//
// Format, one record per line:
//   @<category>              starts a category (picker order)
//   <glyph>\t<name> <name>…  an emoji; the first name is the primary short name
//   ~<glyph>\t<digits>       skin-tone variant of the preceding emoji: each of its
//                            names + "_" + the tones for digits 1…5 joined by "_"
//                            (1 light … 5 dark, e.g. "13" = light_skin_tone_medium_skin_tone)
//   ~<glyph>\t=<name> <name>… skin-tone variant with explicitly listed names

extension EmojiCatalog {
    static let packedSystemEmoji: StaticString = #"""
@smileys-emotion
😀	grinning
😃	smiley
😄	smile
😁	grin
😆	laughing satisfied
😅	sweat_smile
🤣	rolling_on_the_floor_laughing rofl
😂	joy
🙂	slightly_smiling_face
🙃	upside_down_face
😉	wink
😊	blush
😇	innocent
🥰	smiling_face_with_3_hearts
😍	heart_eyes
🤩	star-struck grinning_face_with_star_eyes
😘	kissing_heart
😗	kissing
☺️	relaxed
😚	kissing_closed_eyes
😙	kissing_smiling_eyes
🥲	smiling_face_with_tear
😋	yum
😛	stuck_out_tongue
😜	stuck_out_tongue_winking_eye
🤪	zany_face grinning_face_with_one_large_and_one_small_eye
😝	stuck_out_tongue_closed_eyes
🤑	money_mouth_face
🤗	hugging_face hugs
🤭	face_with_hand_over_mouth smiling_face_with_smiling_eyes_and_hand_covering_mouth
🤫	shushing_face face_with_finger_covering_closed_lips
🤔	thinking_face thinking
🤐	zipper_mouth_face
🤨	face_with_raised_eyebrow face_with_one_eyebrow_raised
😐	neutral_face
😑	expressionless
😶	no_mouth
😏	smirk
😒	unamused
🙄	face_with_rolling_eyes roll_eyes
😬	grimacing
🤥	lying_face
😌	relieved
😔	pensive
😪	sleepy
🤤	drooling_face
😴	sleeping
😷	mask
🤒	face_with_thermometer
🤕	face_with_head_bandage
🤢	nauseated_face
🤮	face_vomiting face_with_open_mouth_vomiting
🤧	sneezing_face
🥵	hot_face
🥶	cold_face
🥴	woozy_face
😵	dizzy_face
🤯	exploding_head shocked_face_with_exploding_head
🤠	face_with_cowboy_hat cowboy_hat_face
🥳	partying_face
🥸	disguised_face
😎	sunglasses
🤓	nerd_face
🧐	face_with_monocle
😕	confused
😟	worried
🙁	slightly_frowning_face
☹️	white_frowning_face frowning_face
😮	open_mouth
😯	hushed
😲	astonished
😳	flushed
🥺	pleading_face
😦	frowning
😧	anguished
😨	fearful
😰	cold_sweat
😥	disappointed_relieved
😢	cry
😭	sob
😱	scream
😖	confounded
😣	persevere
😞	disappointed
😓	sweat
😩	weary
😫	tired_face
🥱	yawning_face
😤	triumph
😡	rage pout
😠	angry
🤬	face_with_symbols_on_mouth serious_face_with_symbols_covering_mouth
😈	smiling_imp
👿	imp
💀	skull
☠️	skull_and_crossbones
💩	hankey poop shit
🤡	clown_face
👹	japanese_ogre
👺	japanese_goblin
👻	ghost
👽	alien
👾	space_invader
🤖	robot_face robot
😺	smiley_cat
😸	smile_cat
😹	joy_cat
😻	heart_eyes_cat
😼	smirk_cat
😽	kissing_cat
🙀	scream_cat
😿	crying_cat_face
😾	pouting_cat
🙈	see_no_evil
🙉	hear_no_evil
🙊	speak_no_evil
💋	kiss
💌	love_letter
💘	cupid
💝	gift_heart
💖	sparkling_heart
💗	heartpulse
💓	heartbeat
💞	revolving_hearts
💕	two_hearts
💟	heart_decoration
❣️	heavy_heart_exclamation_mark_ornament heavy_heart_exclamation
💔	broken_heart
❤️	heart
🧡	orange_heart
💛	yellow_heart
💚	green_heart
💙	blue_heart
💜	purple_heart
🤎	brown_heart
🖤	black_heart
🤍	white_heart
💯	100
💢	anger
💥	boom collision
💫	dizzy
💦	sweat_drops
💨	dash
🕳️	hole
💣	bomb
💬	speech_balloon
👁️‍🗨️	eye-in-speech-bubble
🗨️	left_speech_bubble
🗯️	right_anger_bubble
💭	thought_balloon
💤	zzz
@people-body
👋	wave
~👋🏻	1
~👋🏼	2
~👋🏽	3
~👋🏾	4
~👋🏿	5
🤚	raised_back_of_hand
~🤚🏻	1
~🤚🏼	2
~🤚🏽	3
~🤚🏾	4
~🤚🏿	5
🖐️	raised_hand_with_fingers_splayed
~🖐🏻	1
~🖐🏼	2
~🖐🏽	3
~🖐🏾	4
~🖐🏿	5
✋	hand raised_hand
~✋🏻	1
~✋🏼	2
~✋🏽	3
~✋🏾	4
~✋🏿	5
🖖	spock-hand vulcan_salute
~🖖🏻	1
~🖖🏼	2
~🖖🏽	3
~🖖🏾	4
~🖖🏿	5
👌	ok_hand
~👌🏻	1
~👌🏼	2
~👌🏽	3
~👌🏾	4
~👌🏿	5
🤌	pinched_fingers
~🤌🏻	1
~🤌🏼	2
~🤌🏽	3
~🤌🏾	4
~🤌🏿	5
🤏	pinching_hand
~🤏🏻	1
~🤏🏼	2
~🤏🏽	3
~🤏🏾	4
~🤏🏿	5
✌️	v
~✌🏻	1
~✌🏼	2
~✌🏽	3
~✌🏾	4
~✌🏿	5
🤞	crossed_fingers hand_with_index_and_middle_fingers_crossed
~🤞🏻	1
~🤞🏼	2
~🤞🏽	3
~🤞🏾	4
~🤞🏿	5
🤟	i_love_you_hand_sign
~🤟🏻	1
~🤟🏼	2
~🤟🏽	3
~🤟🏾	4
~🤟🏿	5
🤘	the_horns sign_of_the_horns metal
~🤘🏻	1
~🤘🏼	2
~🤘🏽	3
~🤘🏾	4
~🤘🏿	5
🤙	call_me_hand
~🤙🏻	1
~🤙🏼	2
~🤙🏽	3
~🤙🏾	4
~🤙🏿	5
👈	point_left
~👈🏻	1
~👈🏼	2
~👈🏽	3
~👈🏾	4
~👈🏿	5
👉	point_right
~👉🏻	1
~👉🏼	2
~👉🏽	3
~👉🏾	4
~👉🏿	5
👆	point_up_2
~👆🏻	1
~👆🏼	2
~👆🏽	3
~👆🏾	4
~👆🏿	5
🖕	middle_finger reversed_hand_with_middle_finger_extended fu
~🖕🏻	=middle_finger_light_skin_tone reversed_hand_with_middle_finger_extended_light_skin_tone
~🖕🏼	=middle_finger_medium_light_skin_tone reversed_hand_with_middle_finger_extended_medium_light_skin_tone
~🖕🏽	=middle_finger_medium_skin_tone reversed_hand_with_middle_finger_extended_medium_skin_tone
~🖕🏾	=middle_finger_medium_dark_skin_tone reversed_hand_with_middle_finger_extended_medium_dark_skin_tone
~🖕🏿	=middle_finger_dark_skin_tone reversed_hand_with_middle_finger_extended_dark_skin_tone
👇	point_down
~👇🏻	1
~👇🏼	2
~👇🏽	3
~👇🏾	4
~👇🏿	5
☝️	point_up
~☝🏻	1
~☝🏼	2
~☝🏽	3
~☝🏾	4
~☝🏿	5
👍	+1 thumbsup
~👍🏻	1
~👍🏼	2
~👍🏽	3
~👍🏾	4
~👍🏿	5
👎	-1 thumbsdown
~👎🏻	1
~👎🏼	2
~👎🏽	3
~👎🏾	4
~👎🏿	5
✊	fist fist_raised
~✊🏻	1
~✊🏼	2
~✊🏽	3
~✊🏾	4
~✊🏿	5
👊	facepunch punch fist_oncoming
~👊🏻	1
~👊🏼	2
~👊🏽	3
~👊🏾	4
~👊🏿	5
🤛	left-facing_fist fist_left
~🤛🏻	1
~🤛🏼	2
~🤛🏽	3
~🤛🏾	4
~🤛🏿	5
🤜	right-facing_fist fist_right
~🤜🏻	1
~🤜🏼	2
~🤜🏽	3
~🤜🏾	4
~🤜🏿	5
👏	clap
~👏🏻	1
~👏🏼	2
~👏🏽	3
~👏🏾	4
~👏🏿	5
🙌	raised_hands
~🙌🏻	1
~🙌🏼	2
~🙌🏽	3
~🙌🏾	4
~🙌🏿	5
👐	open_hands
~👐🏻	1
~👐🏼	2
~👐🏽	3
~👐🏾	4
~👐🏿	5
🤲	palms_up_together
~🤲🏻	1
~🤲🏼	2
~🤲🏽	3
~🤲🏾	4
~🤲🏿	5
🤝	handshake
🙏	pray
~🙏🏻	1
~🙏🏼	2
~🙏🏽	3
~🙏🏾	4
~🙏🏿	5
✍️	writing_hand
~✍🏻	1
~✍🏼	2
~✍🏽	3
~✍🏾	4
~✍🏿	5
💅	nail_care
~💅🏻	1
~💅🏼	2
~💅🏽	3
~💅🏾	4
~💅🏿	5
🤳	selfie
~🤳🏻	1
~🤳🏼	2
~🤳🏽	3
~🤳🏾	4
~🤳🏿	5
💪	muscle
~💪🏻	1
~💪🏼	2
~💪🏽	3
~💪🏾	4
~💪🏿	5
🦾	mechanical_arm
🦿	mechanical_leg
🦵	leg
~🦵🏻	1
~🦵🏼	2
~🦵🏽	3
~🦵🏾	4
~🦵🏿	5
🦶	foot
~🦶🏻	1
~🦶🏼	2
~🦶🏽	3
~🦶🏾	4
~🦶🏿	5
👂	ear
~👂🏻	1
~👂🏼	2
~👂🏽	3
~👂🏾	4
~👂🏿	5
🦻	ear_with_hearing_aid
~🦻🏻	1
~🦻🏼	2
~🦻🏽	3
~🦻🏾	4
~🦻🏿	5
👃	nose
~👃🏻	1
~👃🏼	2
~👃🏽	3
~👃🏾	4
~👃🏿	5
🧠	brain
🫀	anatomical_heart
🫁	lungs
🦷	tooth
🦴	bone
👀	eyes
👁️	eye
👅	tongue
👄	lips
👶	baby
~👶🏻	1
~👶🏼	2
~👶🏽	3
~👶🏾	4
~👶🏿	5
🧒	child
~🧒🏻	1
~🧒🏼	2
~🧒🏽	3
~🧒🏾	4
~🧒🏿	5
👦	boy
~👦🏻	1
~👦🏼	2
~👦🏽	3
~👦🏾	4
~👦🏿	5
👧	girl
~👧🏻	1
~👧🏼	2
~👧🏽	3
~👧🏾	4
~👧🏿	5
🧑	adult
~🧑🏻	1
~🧑🏼	2
~🧑🏽	3
~🧑🏾	4
~🧑🏿	5
👱	person_with_blond_hair
~👱🏻	1
~👱🏼	2
~👱🏽	3
~👱🏾	4
~👱🏿	5
👨	man
~👨🏻	1
~👨🏼	2
~👨🏽	3
~👨🏾	4
~👨🏿	5
🧔	bearded_person
~🧔🏻	1
~🧔🏼	2
~🧔🏽	3
~🧔🏾	4
~🧔🏿	5
👨‍🦰	red_haired_man
~👨🏻‍🦰	1
~👨🏼‍🦰	2
~👨🏽‍🦰	3
~👨🏾‍🦰	4
~👨🏿‍🦰	5
👨‍🦱	curly_haired_man
~👨🏻‍🦱	1
~👨🏼‍🦱	2
~👨🏽‍🦱	3
~👨🏾‍🦱	4
~👨🏿‍🦱	5
👨‍🦳	white_haired_man
~👨🏻‍🦳	1
~👨🏼‍🦳	2
~👨🏽‍🦳	3
~👨🏾‍🦳	4
~👨🏿‍🦳	5
👨‍🦲	bald_man
~👨🏻‍🦲	1
~👨🏼‍🦲	2
~👨🏽‍🦲	3
~👨🏾‍🦲	4
~👨🏿‍🦲	5
👩	woman
~👩🏻	1
~👩🏼	2
~👩🏽	3
~👩🏾	4
~👩🏿	5
👩‍🦰	red_haired_woman
~👩🏻‍🦰	1
~👩🏼‍🦰	2
~👩🏽‍🦰	3
~👩🏾‍🦰	4
~👩🏿‍🦰	5
🧑‍🦰	red_haired_person
~🧑🏻‍🦰	1
~🧑🏼‍🦰	2
~🧑🏽‍🦰	3
~🧑🏾‍🦰	4
~🧑🏿‍🦰	5
👩‍🦱	curly_haired_woman
~👩🏻‍🦱	1
~👩🏼‍🦱	2
~👩🏽‍🦱	3
~👩🏾‍🦱	4
~👩🏿‍🦱	5
🧑‍🦱	curly_haired_person
~🧑🏻‍🦱	1
~🧑🏼‍🦱	2
~🧑🏽‍🦱	3
~🧑🏾‍🦱	4
~🧑🏿‍🦱	5
👩‍🦳	white_haired_woman
~👩🏻‍🦳	1
~👩🏼‍🦳	2
~👩🏽‍🦳	3
~👩🏾‍🦳	4
~👩🏿‍🦳	5
🧑‍🦳	white_haired_person
~🧑🏻‍🦳	1
~🧑🏼‍🦳	2
~🧑🏽‍🦳	3
~🧑🏾‍🦳	4
~🧑🏿‍🦳	5
👩‍🦲	bald_woman
~👩🏻‍🦲	1
~👩🏼‍🦲	2
~👩🏽‍🦲	3
~👩🏾‍🦲	4
~👩🏿‍🦲	5
🧑‍🦲	bald_person
~🧑🏻‍🦲	1
~🧑🏼‍🦲	2
~🧑🏽‍🦲	3
~🧑🏾‍🦲	4
~🧑🏿‍🦲	5
👱‍♀️	blond-haired-woman blonde_woman
~👱🏻‍♀️	1
~👱🏼‍♀️	2
~👱🏽‍♀️	3
~👱🏾‍♀️	4
~👱🏿‍♀️	5
👱‍♂️	blond-haired-man blonde_man
~👱🏻‍♂️	1
~👱🏼‍♂️	2
~👱🏽‍♂️	3
~👱🏾‍♂️	4
~👱🏿‍♂️	5
🧓	older_adult
~🧓🏻	1
~🧓🏼	2
~🧓🏽	3
~🧓🏾	4
~🧓🏿	5
👴	older_man
~👴🏻	1
~👴🏼	2
~👴🏽	3
~👴🏾	4
~👴🏿	5
👵	older_woman
~👵🏻	1
~👵🏼	2
~👵🏽	3
~👵🏾	4
~👵🏿	5
🙍	person_frowning
~🙍🏻	1
~🙍🏼	2
~🙍🏽	3
~🙍🏾	4
~🙍🏿	5
🙍‍♂️	man-frowning frowning_man
~🙍🏻‍♂️	1
~🙍🏼‍♂️	2
~🙍🏽‍♂️	3
~🙍🏾‍♂️	4
~🙍🏿‍♂️	5
🙍‍♀️	woman-frowning frowning_woman
~🙍🏻‍♀️	1
~🙍🏼‍♀️	2
~🙍🏽‍♀️	3
~🙍🏾‍♀️	4
~🙍🏿‍♀️	5
🙎	person_with_pouting_face
~🙎🏻	1
~🙎🏼	2
~🙎🏽	3
~🙎🏾	4
~🙎🏿	5
🙎‍♂️	man-pouting pouting_man
~🙎🏻‍♂️	1
~🙎🏼‍♂️	2
~🙎🏽‍♂️	3
~🙎🏾‍♂️	4
~🙎🏿‍♂️	5
🙎‍♀️	woman-pouting pouting_woman
~🙎🏻‍♀️	1
~🙎🏼‍♀️	2
~🙎🏽‍♀️	3
~🙎🏾‍♀️	4
~🙎🏿‍♀️	5
🙅	no_good
~🙅🏻	1
~🙅🏼	2
~🙅🏽	3
~🙅🏾	4
~🙅🏿	5
🙅‍♂️	man-gesturing-no ng_man no_good_man
~🙅🏻‍♂️	=man-gesturing-no_light_skin_tone no_good_man_light_skin_tone
~🙅🏼‍♂️	=man-gesturing-no_medium_light_skin_tone no_good_man_medium_light_skin_tone
~🙅🏽‍♂️	=man-gesturing-no_medium_skin_tone no_good_man_medium_skin_tone
~🙅🏾‍♂️	=man-gesturing-no_medium_dark_skin_tone no_good_man_medium_dark_skin_tone
~🙅🏿‍♂️	=man-gesturing-no_dark_skin_tone no_good_man_dark_skin_tone
🙅‍♀️	woman-gesturing-no no_good_woman ng_woman
~🙅🏻‍♀️	=woman-gesturing-no_light_skin_tone no_good_woman_light_skin_tone
~🙅🏼‍♀️	=woman-gesturing-no_medium_light_skin_tone no_good_woman_medium_light_skin_tone
~🙅🏽‍♀️	=woman-gesturing-no_medium_skin_tone no_good_woman_medium_skin_tone
~🙅🏾‍♀️	=woman-gesturing-no_medium_dark_skin_tone no_good_woman_medium_dark_skin_tone
~🙅🏿‍♀️	=woman-gesturing-no_dark_skin_tone no_good_woman_dark_skin_tone
🙆	ok_woman
~🙆🏻	1
~🙆🏼	2
~🙆🏽	3
~🙆🏾	4
~🙆🏿	5
🙆‍♂️	man-gesturing-ok ok_man
~🙆🏻‍♂️	1
~🙆🏼‍♂️	2
~🙆🏽‍♂️	3
~🙆🏾‍♂️	4
~🙆🏿‍♂️	5
🙆‍♀️	woman-gesturing-ok
~🙆🏻‍♀️	1
~🙆🏼‍♀️	2
~🙆🏽‍♀️	3
~🙆🏾‍♀️	4
~🙆🏿‍♀️	5
💁	information_desk_person
~💁🏻	1
~💁🏼	2
~💁🏽	3
~💁🏾	4
~💁🏿	5
💁‍♂️	man-tipping-hand tipping_hand_man
~💁🏻‍♂️	1
~💁🏼‍♂️	2
~💁🏽‍♂️	3
~💁🏾‍♂️	4
~💁🏿‍♂️	5
💁‍♀️	woman-tipping-hand tipping_hand_woman
~💁🏻‍♀️	1
~💁🏼‍♀️	2
~💁🏽‍♀️	3
~💁🏾‍♀️	4
~💁🏿‍♀️	5
🙋	raising_hand
~🙋🏻	1
~🙋🏼	2
~🙋🏽	3
~🙋🏾	4
~🙋🏿	5
🙋‍♂️	man-raising-hand raising_hand_man
~🙋🏻‍♂️	1
~🙋🏼‍♂️	2
~🙋🏽‍♂️	3
~🙋🏾‍♂️	4
~🙋🏿‍♂️	5
🙋‍♀️	woman-raising-hand raising_hand_woman
~🙋🏻‍♀️	1
~🙋🏼‍♀️	2
~🙋🏽‍♀️	3
~🙋🏾‍♀️	4
~🙋🏿‍♀️	5
🧏	deaf_person
~🧏🏻	1
~🧏🏼	2
~🧏🏽	3
~🧏🏾	4
~🧏🏿	5
🧏‍♂️	deaf_man
~🧏🏻‍♂️	1
~🧏🏼‍♂️	2
~🧏🏽‍♂️	3
~🧏🏾‍♂️	4
~🧏🏿‍♂️	5
🧏‍♀️	deaf_woman
~🧏🏻‍♀️	1
~🧏🏼‍♀️	2
~🧏🏽‍♀️	3
~🧏🏾‍♀️	4
~🧏🏿‍♀️	5
🙇	bow
~🙇🏻	1
~🙇🏼	2
~🙇🏽	3
~🙇🏾	4
~🙇🏿	5
🙇‍♂️	man-bowing bowing_man
~🙇🏻‍♂️	1
~🙇🏼‍♂️	2
~🙇🏽‍♂️	3
~🙇🏾‍♂️	4
~🙇🏿‍♂️	5
🙇‍♀️	woman-bowing bowing_woman
~🙇🏻‍♀️	1
~🙇🏼‍♀️	2
~🙇🏽‍♀️	3
~🙇🏾‍♀️	4
~🙇🏿‍♀️	5
🤦	face_palm
~🤦🏻	1
~🤦🏼	2
~🤦🏽	3
~🤦🏾	4
~🤦🏿	5
🤦‍♂️	man-facepalming man_facepalming
~🤦🏻‍♂️	1
~🤦🏼‍♂️	2
~🤦🏽‍♂️	3
~🤦🏾‍♂️	4
~🤦🏿‍♂️	5
🤦‍♀️	woman-facepalming woman_facepalming
~🤦🏻‍♀️	1
~🤦🏼‍♀️	2
~🤦🏽‍♀️	3
~🤦🏾‍♀️	4
~🤦🏿‍♀️	5
🤷	shrug
~🤷🏻	1
~🤷🏼	2
~🤷🏽	3
~🤷🏾	4
~🤷🏿	5
🤷‍♂️	man-shrugging man_shrugging
~🤷🏻‍♂️	1
~🤷🏼‍♂️	2
~🤷🏽‍♂️	3
~🤷🏾‍♂️	4
~🤷🏿‍♂️	5
🤷‍♀️	woman-shrugging woman_shrugging
~🤷🏻‍♀️	1
~🤷🏼‍♀️	2
~🤷🏽‍♀️	3
~🤷🏾‍♀️	4
~🤷🏿‍♀️	5
🧑‍⚕️	health_worker doctor
~🧑🏻‍⚕️	1
~🧑🏼‍⚕️	2
~🧑🏽‍⚕️	3
~🧑🏾‍⚕️	4
~🧑🏿‍⚕️	5
👨‍⚕️	male-doctor man_health_worker
~👨🏻‍⚕️	1
~👨🏼‍⚕️	2
~👨🏽‍⚕️	3
~👨🏾‍⚕️	4
~👨🏿‍⚕️	5
👩‍⚕️	female-doctor woman_health_worker
~👩🏻‍⚕️	1
~👩🏼‍⚕️	2
~👩🏽‍⚕️	3
~👩🏾‍⚕️	4
~👩🏿‍⚕️	5
🧑‍🎓	student
~🧑🏻‍🎓	1
~🧑🏼‍🎓	2
~🧑🏽‍🎓	3
~🧑🏾‍🎓	4
~🧑🏿‍🎓	5
👨‍🎓	male-student man_student
~👨🏻‍🎓	1
~👨🏼‍🎓	2
~👨🏽‍🎓	3
~👨🏾‍🎓	4
~👨🏿‍🎓	5
👩‍🎓	female-student woman_student
~👩🏻‍🎓	1
~👩🏼‍🎓	2
~👩🏽‍🎓	3
~👩🏾‍🎓	4
~👩🏿‍🎓	5
🧑‍🏫	teacher
~🧑🏻‍🏫	1
~🧑🏼‍🏫	2
~🧑🏽‍🏫	3
~🧑🏾‍🏫	4
~🧑🏿‍🏫	5
👨‍🏫	male-teacher man_teacher
~👨🏻‍🏫	1
~👨🏼‍🏫	2
~👨🏽‍🏫	3
~👨🏾‍🏫	4
~👨🏿‍🏫	5
👩‍🏫	female-teacher woman_teacher
~👩🏻‍🏫	1
~👩🏼‍🏫	2
~👩🏽‍🏫	3
~👩🏾‍🏫	4
~👩🏿‍🏫	5
🧑‍⚖️	judge
~🧑🏻‍⚖️	1
~🧑🏼‍⚖️	2
~🧑🏽‍⚖️	3
~🧑🏾‍⚖️	4
~🧑🏿‍⚖️	5
👨‍⚖️	male-judge man_judge
~👨🏻‍⚖️	1
~👨🏼‍⚖️	2
~👨🏽‍⚖️	3
~👨🏾‍⚖️	4
~👨🏿‍⚖️	5
👩‍⚖️	female-judge woman_judge
~👩🏻‍⚖️	1
~👩🏼‍⚖️	2
~👩🏽‍⚖️	3
~👩🏾‍⚖️	4
~👩🏿‍⚖️	5
🧑‍🌾	farmer
~🧑🏻‍🌾	1
~🧑🏼‍🌾	2
~🧑🏽‍🌾	3
~🧑🏾‍🌾	4
~🧑🏿‍🌾	5
👨‍🌾	male-farmer man_farmer
~👨🏻‍🌾	1
~👨🏼‍🌾	2
~👨🏽‍🌾	3
~👨🏾‍🌾	4
~👨🏿‍🌾	5
👩‍🌾	female-farmer woman_farmer
~👩🏻‍🌾	1
~👩🏼‍🌾	2
~👩🏽‍🌾	3
~👩🏾‍🌾	4
~👩🏿‍🌾	5
🧑‍🍳	cook
~🧑🏻‍🍳	1
~🧑🏼‍🍳	2
~🧑🏽‍🍳	3
~🧑🏾‍🍳	4
~🧑🏿‍🍳	5
👨‍🍳	male-cook man_cook
~👨🏻‍🍳	1
~👨🏼‍🍳	2
~👨🏽‍🍳	3
~👨🏾‍🍳	4
~👨🏿‍🍳	5
👩‍🍳	female-cook woman_cook
~👩🏻‍🍳	1
~👩🏼‍🍳	2
~👩🏽‍🍳	3
~👩🏾‍🍳	4
~👩🏿‍🍳	5
🧑‍🔧	mechanic
~🧑🏻‍🔧	1
~🧑🏼‍🔧	2
~🧑🏽‍🔧	3
~🧑🏾‍🔧	4
~🧑🏿‍🔧	5
👨‍🔧	male-mechanic man_mechanic
~👨🏻‍🔧	1
~👨🏼‍🔧	2
~👨🏽‍🔧	3
~👨🏾‍🔧	4
~👨🏿‍🔧	5
👩‍🔧	female-mechanic woman_mechanic
~👩🏻‍🔧	1
~👩🏼‍🔧	2
~👩🏽‍🔧	3
~👩🏾‍🔧	4
~👩🏿‍🔧	5
🧑‍🏭	factory_worker
~🧑🏻‍🏭	1
~🧑🏼‍🏭	2
~🧑🏽‍🏭	3
~🧑🏾‍🏭	4
~🧑🏿‍🏭	5
👨‍🏭	male-factory-worker man_factory_worker
~👨🏻‍🏭	1
~👨🏼‍🏭	2
~👨🏽‍🏭	3
~👨🏾‍🏭	4
~👨🏿‍🏭	5
👩‍🏭	female-factory-worker woman_factory_worker
~👩🏻‍🏭	1
~👩🏼‍🏭	2
~👩🏽‍🏭	3
~👩🏾‍🏭	4
~👩🏿‍🏭	5
🧑‍💼	office_worker
~🧑🏻‍💼	1
~🧑🏼‍💼	2
~🧑🏽‍💼	3
~🧑🏾‍💼	4
~🧑🏿‍💼	5
👨‍💼	male-office-worker man_office_worker
~👨🏻‍💼	1
~👨🏼‍💼	2
~👨🏽‍💼	3
~👨🏾‍💼	4
~👨🏿‍💼	5
👩‍💼	female-office-worker woman_office_worker
~👩🏻‍💼	1
~👩🏼‍💼	2
~👩🏽‍💼	3
~👩🏾‍💼	4
~👩🏿‍💼	5
🧑‍🔬	scientist
~🧑🏻‍🔬	1
~🧑🏼‍🔬	2
~🧑🏽‍🔬	3
~🧑🏾‍🔬	4
~🧑🏿‍🔬	5
👨‍🔬	male-scientist man_scientist
~👨🏻‍🔬	1
~👨🏼‍🔬	2
~👨🏽‍🔬	3
~👨🏾‍🔬	4
~👨🏿‍🔬	5
👩‍🔬	female-scientist woman_scientist
~👩🏻‍🔬	1
~👩🏼‍🔬	2
~👩🏽‍🔬	3
~👩🏾‍🔬	4
~👩🏿‍🔬	5
🧑‍💻	technologist
~🧑🏻‍💻	1
~🧑🏼‍💻	2
~🧑🏽‍💻	3
~🧑🏾‍💻	4
~🧑🏿‍💻	5
👨‍💻	male-technologist man_technologist
~👨🏻‍💻	1
~👨🏼‍💻	2
~👨🏽‍💻	3
~👨🏾‍💻	4
~👨🏿‍💻	5
👩‍💻	female-technologist woman_technologist
~👩🏻‍💻	1
~👩🏼‍💻	2
~👩🏽‍💻	3
~👩🏾‍💻	4
~👩🏿‍💻	5
🧑‍🎤	singer
~🧑🏻‍🎤	1
~🧑🏼‍🎤	2
~🧑🏽‍🎤	3
~🧑🏾‍🎤	4
~🧑🏿‍🎤	5
👨‍🎤	male-singer man_singer
~👨🏻‍🎤	1
~👨🏼‍🎤	2
~👨🏽‍🎤	3
~👨🏾‍🎤	4
~👨🏿‍🎤	5
👩‍🎤	female-singer woman_singer
~👩🏻‍🎤	1
~👩🏼‍🎤	2
~👩🏽‍🎤	3
~👩🏾‍🎤	4
~👩🏿‍🎤	5
🧑‍🎨	artist
~🧑🏻‍🎨	1
~🧑🏼‍🎨	2
~🧑🏽‍🎨	3
~🧑🏾‍🎨	4
~🧑🏿‍🎨	5
👨‍🎨	male-artist man_artist
~👨🏻‍🎨	1
~👨🏼‍🎨	2
~👨🏽‍🎨	3
~👨🏾‍🎨	4
~👨🏿‍🎨	5
👩‍🎨	female-artist woman_artist
~👩🏻‍🎨	1
~👩🏼‍🎨	2
~👩🏽‍🎨	3
~👩🏾‍🎨	4
~👩🏿‍🎨	5
🧑‍✈️	pilot
~🧑🏻‍✈️	1
~🧑🏼‍✈️	2
~🧑🏽‍✈️	3
~🧑🏾‍✈️	4
~🧑🏿‍✈️	5
👨‍✈️	male-pilot man_pilot
~👨🏻‍✈️	1
~👨🏼‍✈️	2
~👨🏽‍✈️	3
~👨🏾‍✈️	4
~👨🏿‍✈️	5
👩‍✈️	female-pilot woman_pilot
~👩🏻‍✈️	1
~👩🏼‍✈️	2
~👩🏽‍✈️	3
~👩🏾‍✈️	4
~👩🏿‍✈️	5
🧑‍🚀	astronaut
~🧑🏻‍🚀	1
~🧑🏼‍🚀	2
~🧑🏽‍🚀	3
~🧑🏾‍🚀	4
~🧑🏿‍🚀	5
👨‍🚀	male-astronaut man_astronaut
~👨🏻‍🚀	1
~👨🏼‍🚀	2
~👨🏽‍🚀	3
~👨🏾‍🚀	4
~👨🏿‍🚀	5
👩‍🚀	female-astronaut woman_astronaut
~👩🏻‍🚀	1
~👩🏼‍🚀	2
~👩🏽‍🚀	3
~👩🏾‍🚀	4
~👩🏿‍🚀	5
🧑‍🚒	firefighter
~🧑🏻‍🚒	1
~🧑🏼‍🚒	2
~🧑🏽‍🚒	3
~🧑🏾‍🚒	4
~🧑🏿‍🚒	5
👨‍🚒	male-firefighter man_firefighter
~👨🏻‍🚒	1
~👨🏼‍🚒	2
~👨🏽‍🚒	3
~👨🏾‍🚒	4
~👨🏿‍🚒	5
👩‍🚒	female-firefighter woman_firefighter
~👩🏻‍🚒	1
~👩🏼‍🚒	2
~👩🏽‍🚒	3
~👩🏾‍🚒	4
~👩🏿‍🚒	5
👮	cop
~👮🏻	1
~👮🏼	2
~👮🏽	3
~👮🏾	4
~👮🏿	5
👮‍♂️	male-police-officer policeman
~👮🏻‍♂️	1
~👮🏼‍♂️	2
~👮🏽‍♂️	3
~👮🏾‍♂️	4
~👮🏿‍♂️	5
👮‍♀️	female-police-officer policewoman
~👮🏻‍♀️	1
~👮🏼‍♀️	2
~👮🏽‍♀️	3
~👮🏾‍♀️	4
~👮🏿‍♀️	5
🕵️	sleuth_or_spy detective
~🕵🏻	=sleuth_or_spy_light_skin_tone
~🕵🏼	=sleuth_or_spy_medium_light_skin_tone
~🕵🏽	=sleuth_or_spy_medium_skin_tone
~🕵🏾	=sleuth_or_spy_medium_dark_skin_tone
~🕵🏿	=sleuth_or_spy_dark_skin_tone
🕵️‍♂️	male-detective male_detective
~🕵🏻‍♂️	1
~🕵🏼‍♂️	2
~🕵🏽‍♂️	3
~🕵🏾‍♂️	4
~🕵🏿‍♂️	5
🕵️‍♀️	female-detective female_detective
~🕵🏻‍♀️	1
~🕵🏼‍♀️	2
~🕵🏽‍♀️	3
~🕵🏾‍♀️	4
~🕵🏿‍♀️	5
💂	guardsman
~💂🏻	1
~💂🏼	2
~💂🏽	3
~💂🏾	4
~💂🏿	5
💂‍♂️	male-guard
~💂🏻‍♂️	1
~💂🏼‍♂️	2
~💂🏽‍♂️	3
~💂🏾‍♂️	4
~💂🏿‍♂️	5
💂‍♀️	female-guard guardswoman
~💂🏻‍♀️	1
~💂🏼‍♀️	2
~💂🏽‍♀️	3
~💂🏾‍♀️	4
~💂🏿‍♀️	5
🥷	ninja
~🥷🏻	1
~🥷🏼	2
~🥷🏽	3
~🥷🏾	4
~🥷🏿	5
👷	construction_worker
~👷🏻	1
~👷🏼	2
~👷🏽	3
~👷🏾	4
~👷🏿	5
👷‍♂️	male-construction-worker construction_worker_man
~👷🏻‍♂️	1
~👷🏼‍♂️	2
~👷🏽‍♂️	3
~👷🏾‍♂️	4
~👷🏿‍♂️	5
👷‍♀️	female-construction-worker construction_worker_woman
~👷🏻‍♀️	1
~👷🏼‍♀️	2
~👷🏽‍♀️	3
~👷🏾‍♀️	4
~👷🏿‍♀️	5
🤴	prince
~🤴🏻	1
~🤴🏼	2
~🤴🏽	3
~🤴🏾	4
~🤴🏿	5
👸	princess
~👸🏻	1
~👸🏼	2
~👸🏽	3
~👸🏾	4
~👸🏿	5
👳	man_with_turban
~👳🏻	1
~👳🏼	2
~👳🏽	3
~👳🏾	4
~👳🏿	5
👳‍♂️	man-wearing-turban
~👳🏻‍♂️	1
~👳🏼‍♂️	2
~👳🏽‍♂️	3
~👳🏾‍♂️	4
~👳🏿‍♂️	5
👳‍♀️	woman-wearing-turban woman_with_turban
~👳🏻‍♀️	1
~👳🏼‍♀️	2
~👳🏽‍♀️	3
~👳🏾‍♀️	4
~👳🏿‍♀️	5
👲	man_with_gua_pi_mao
~👲🏻	1
~👲🏼	2
~👲🏽	3
~👲🏾	4
~👲🏿	5
🧕	person_with_headscarf
~🧕🏻	1
~🧕🏼	2
~🧕🏽	3
~🧕🏾	4
~🧕🏿	5
🤵	person_in_tuxedo
~🤵🏻	1
~🤵🏼	2
~🤵🏽	3
~🤵🏾	4
~🤵🏿	5
🤵‍♂️	man_in_tuxedo
~🤵🏻‍♂️	1
~🤵🏼‍♂️	2
~🤵🏽‍♂️	3
~🤵🏾‍♂️	4
~🤵🏿‍♂️	5
🤵‍♀️	woman_in_tuxedo
~🤵🏻‍♀️	1
~🤵🏼‍♀️	2
~🤵🏽‍♀️	3
~🤵🏾‍♀️	4
~🤵🏿‍♀️	5
👰	bride_with_veil
~👰🏻	1
~👰🏼	2
~👰🏽	3
~👰🏾	4
~👰🏿	5
👰‍♂️	man_with_veil
~👰🏻‍♂️	1
~👰🏼‍♂️	2
~👰🏽‍♂️	3
~👰🏾‍♂️	4
~👰🏿‍♂️	5
👰‍♀️	woman_with_veil
~👰🏻‍♀️	1
~👰🏼‍♀️	2
~👰🏽‍♀️	3
~👰🏾‍♀️	4
~👰🏿‍♀️	5
🤰	pregnant_woman
~🤰🏻	1
~🤰🏼	2
~🤰🏽	3
~🤰🏾	4
~🤰🏿	5
🤱	breast-feeding
~🤱🏻	1
~🤱🏼	2
~🤱🏽	3
~🤱🏾	4
~🤱🏿	5
👩‍🍼	woman_feeding_baby
~👩🏻‍🍼	1
~👩🏼‍🍼	2
~👩🏽‍🍼	3
~👩🏾‍🍼	4
~👩🏿‍🍼	5
👨‍🍼	man_feeding_baby
~👨🏻‍🍼	1
~👨🏼‍🍼	2
~👨🏽‍🍼	3
~👨🏾‍🍼	4
~👨🏿‍🍼	5
🧑‍🍼	person_feeding_baby
~🧑🏻‍🍼	1
~🧑🏼‍🍼	2
~🧑🏽‍🍼	3
~🧑🏾‍🍼	4
~🧑🏿‍🍼	5
👼	angel
~👼🏻	1
~👼🏼	2
~👼🏽	3
~👼🏾	4
~👼🏿	5
🎅	santa
~🎅🏻	1
~🎅🏼	2
~🎅🏽	3
~🎅🏾	4
~🎅🏿	5
🤶	mrs_claus mother_christmas
~🤶🏻	1
~🤶🏼	2
~🤶🏽	3
~🤶🏾	4
~🤶🏿	5
🧑‍🎄	mx_claus
~🧑🏻‍🎄	1
~🧑🏼‍🎄	2
~🧑🏽‍🎄	3
~🧑🏾‍🎄	4
~🧑🏿‍🎄	5
🦸	superhero
~🦸🏻	1
~🦸🏼	2
~🦸🏽	3
~🦸🏾	4
~🦸🏿	5
🦸‍♂️	male_superhero
~🦸🏻‍♂️	1
~🦸🏼‍♂️	2
~🦸🏽‍♂️	3
~🦸🏾‍♂️	4
~🦸🏿‍♂️	5
🦸‍♀️	female_superhero
~🦸🏻‍♀️	1
~🦸🏼‍♀️	2
~🦸🏽‍♀️	3
~🦸🏾‍♀️	4
~🦸🏿‍♀️	5
🦹	supervillain
~🦹🏻	1
~🦹🏼	2
~🦹🏽	3
~🦹🏾	4
~🦹🏿	5
🦹‍♂️	male_supervillain
~🦹🏻‍♂️	1
~🦹🏼‍♂️	2
~🦹🏽‍♂️	3
~🦹🏾‍♂️	4
~🦹🏿‍♂️	5
🦹‍♀️	female_supervillain
~🦹🏻‍♀️	1
~🦹🏼‍♀️	2
~🦹🏽‍♀️	3
~🦹🏾‍♀️	4
~🦹🏿‍♀️	5
🧙	mage
~🧙🏻	1
~🧙🏼	2
~🧙🏽	3
~🧙🏾	4
~🧙🏿	5
🧙‍♂️	male_mage
~🧙🏻‍♂️	1
~🧙🏼‍♂️	2
~🧙🏽‍♂️	3
~🧙🏾‍♂️	4
~🧙🏿‍♂️	5
🧙‍♀️	female_mage
~🧙🏻‍♀️	1
~🧙🏼‍♀️	2
~🧙🏽‍♀️	3
~🧙🏾‍♀️	4
~🧙🏿‍♀️	5
🧚	fairy
~🧚🏻	1
~🧚🏼	2
~🧚🏽	3
~🧚🏾	4
~🧚🏿	5
🧚‍♂️	male_fairy
~🧚🏻‍♂️	1
~🧚🏼‍♂️	2
~🧚🏽‍♂️	3
~🧚🏾‍♂️	4
~🧚🏿‍♂️	5
🧚‍♀️	female_fairy
~🧚🏻‍♀️	1
~🧚🏼‍♀️	2
~🧚🏽‍♀️	3
~🧚🏾‍♀️	4
~🧚🏿‍♀️	5
🧛	vampire
~🧛🏻	1
~🧛🏼	2
~🧛🏽	3
~🧛🏾	4
~🧛🏿	5
🧛‍♂️	male_vampire
~🧛🏻‍♂️	1
~🧛🏼‍♂️	2
~🧛🏽‍♂️	3
~🧛🏾‍♂️	4
~🧛🏿‍♂️	5
🧛‍♀️	female_vampire
~🧛🏻‍♀️	1
~🧛🏼‍♀️	2
~🧛🏽‍♀️	3
~🧛🏾‍♀️	4
~🧛🏿‍♀️	5
🧜	merperson
~🧜🏻	1
~🧜🏼	2
~🧜🏽	3
~🧜🏾	4
~🧜🏿	5
🧜‍♂️	merman
~🧜🏻‍♂️	1
~🧜🏼‍♂️	2
~🧜🏽‍♂️	3
~🧜🏾‍♂️	4
~🧜🏿‍♂️	5
🧜‍♀️	mermaid
~🧜🏻‍♀️	1
~🧜🏼‍♀️	2
~🧜🏽‍♀️	3
~🧜🏾‍♀️	4
~🧜🏿‍♀️	5
🧝	elf
~🧝🏻	1
~🧝🏼	2
~🧝🏽	3
~🧝🏾	4
~🧝🏿	5
🧝‍♂️	male_elf
~🧝🏻‍♂️	1
~🧝🏼‍♂️	2
~🧝🏽‍♂️	3
~🧝🏾‍♂️	4
~🧝🏿‍♂️	5
🧝‍♀️	female_elf
~🧝🏻‍♀️	1
~🧝🏼‍♀️	2
~🧝🏽‍♀️	3
~🧝🏾‍♀️	4
~🧝🏿‍♀️	5
🧞	genie
🧞‍♂️	male_genie
🧞‍♀️	female_genie
🧟	zombie
🧟‍♂️	male_zombie
🧟‍♀️	female_zombie
💆	massage
~💆🏻	1
~💆🏼	2
~💆🏽	3
~💆🏾	4
~💆🏿	5
💆‍♂️	man-getting-massage massage_man
~💆🏻‍♂️	1
~💆🏼‍♂️	2
~💆🏽‍♂️	3
~💆🏾‍♂️	4
~💆🏿‍♂️	5
💆‍♀️	woman-getting-massage massage_woman
~💆🏻‍♀️	1
~💆🏼‍♀️	2
~💆🏽‍♀️	3
~💆🏾‍♀️	4
~💆🏿‍♀️	5
💇	haircut
~💇🏻	1
~💇🏼	2
~💇🏽	3
~💇🏾	4
~💇🏿	5
💇‍♂️	man-getting-haircut haircut_man
~💇🏻‍♂️	1
~💇🏼‍♂️	2
~💇🏽‍♂️	3
~💇🏾‍♂️	4
~💇🏿‍♂️	5
💇‍♀️	woman-getting-haircut haircut_woman
~💇🏻‍♀️	1
~💇🏼‍♀️	2
~💇🏽‍♀️	3
~💇🏾‍♀️	4
~💇🏿‍♀️	5
🚶	walking
~🚶🏻	1
~🚶🏼	2
~🚶🏽	3
~🚶🏾	4
~🚶🏿	5
🚶‍♂️	man-walking walking_man
~🚶🏻‍♂️	1
~🚶🏼‍♂️	2
~🚶🏽‍♂️	3
~🚶🏾‍♂️	4
~🚶🏿‍♂️	5
🚶‍♀️	woman-walking walking_woman
~🚶🏻‍♀️	1
~🚶🏼‍♀️	2
~🚶🏽‍♀️	3
~🚶🏾‍♀️	4
~🚶🏿‍♀️	5
🧍	standing_person
~🧍🏻	1
~🧍🏼	2
~🧍🏽	3
~🧍🏾	4
~🧍🏿	5
🧍‍♂️	man_standing
~🧍🏻‍♂️	1
~🧍🏼‍♂️	2
~🧍🏽‍♂️	3
~🧍🏾‍♂️	4
~🧍🏿‍♂️	5
🧍‍♀️	woman_standing
~🧍🏻‍♀️	1
~🧍🏼‍♀️	2
~🧍🏽‍♀️	3
~🧍🏾‍♀️	4
~🧍🏿‍♀️	5
🧎	kneeling_person
~🧎🏻	1
~🧎🏼	2
~🧎🏽	3
~🧎🏾	4
~🧎🏿	5
🧎‍♂️	man_kneeling
~🧎🏻‍♂️	1
~🧎🏼‍♂️	2
~🧎🏽‍♂️	3
~🧎🏾‍♂️	4
~🧎🏿‍♂️	5
🧎‍♀️	woman_kneeling
~🧎🏻‍♀️	1
~🧎🏼‍♀️	2
~🧎🏽‍♀️	3
~🧎🏾‍♀️	4
~🧎🏿‍♀️	5
🧑‍🦯	person_with_probing_cane
~🧑🏻‍🦯	1
~🧑🏼‍🦯	2
~🧑🏽‍🦯	3
~🧑🏾‍🦯	4
~🧑🏿‍🦯	5
👨‍🦯	man_with_probing_cane
~👨🏻‍🦯	1
~👨🏼‍🦯	2
~👨🏽‍🦯	3
~👨🏾‍🦯	4
~👨🏿‍🦯	5
👩‍🦯	woman_with_probing_cane
~👩🏻‍🦯	1
~👩🏼‍🦯	2
~👩🏽‍🦯	3
~👩🏾‍🦯	4
~👩🏿‍🦯	5
🧑‍🦼	person_in_motorized_wheelchair
~🧑🏻‍🦼	1
~🧑🏼‍🦼	2
~🧑🏽‍🦼	3
~🧑🏾‍🦼	4
~🧑🏿‍🦼	5
👨‍🦼	man_in_motorized_wheelchair
~👨🏻‍🦼	1
~👨🏼‍🦼	2
~👨🏽‍🦼	3
~👨🏾‍🦼	4
~👨🏿‍🦼	5
👩‍🦼	woman_in_motorized_wheelchair
~👩🏻‍🦼	1
~👩🏼‍🦼	2
~👩🏽‍🦼	3
~👩🏾‍🦼	4
~👩🏿‍🦼	5
🧑‍🦽	person_in_manual_wheelchair
~🧑🏻‍🦽	1
~🧑🏼‍🦽	2
~🧑🏽‍🦽	3
~🧑🏾‍🦽	4
~🧑🏿‍🦽	5
👨‍🦽	man_in_manual_wheelchair
~👨🏻‍🦽	1
~👨🏼‍🦽	2
~👨🏽‍🦽	3
~👨🏾‍🦽	4
~👨🏿‍🦽	5
👩‍🦽	woman_in_manual_wheelchair
~👩🏻‍🦽	1
~👩🏼‍🦽	2
~👩🏽‍🦽	3
~👩🏾‍🦽	4
~👩🏿‍🦽	5
🏃	runner running
~🏃🏻	1
~🏃🏼	2
~🏃🏽	3
~🏃🏾	4
~🏃🏿	5
🏃‍♂️	man-running running_man
~🏃🏻‍♂️	1
~🏃🏼‍♂️	2
~🏃🏽‍♂️	3
~🏃🏾‍♂️	4
~🏃🏿‍♂️	5
🏃‍♀️	woman-running running_woman
~🏃🏻‍♀️	1
~🏃🏼‍♀️	2
~🏃🏽‍♀️	3
~🏃🏾‍♀️	4
~🏃🏿‍♀️	5
💃	dancer
~💃🏻	1
~💃🏼	2
~💃🏽	3
~💃🏾	4
~💃🏿	5
🕺	man_dancing
~🕺🏻	1
~🕺🏼	2
~🕺🏽	3
~🕺🏾	4
~🕺🏿	5
🕴️	man_in_business_suit_levitating business_suit_levitating
~🕴🏻	1
~🕴🏼	2
~🕴🏽	3
~🕴🏾	4
~🕴🏿	5
👯	dancers
👯‍♂️	man-with-bunny-ears-partying dancing_men
👯‍♀️	woman-with-bunny-ears-partying dancing_women
🧖	person_in_steamy_room
~🧖🏻	1
~🧖🏼	2
~🧖🏽	3
~🧖🏾	4
~🧖🏿	5
🧖‍♂️	man_in_steamy_room
~🧖🏻‍♂️	1
~🧖🏼‍♂️	2
~🧖🏽‍♂️	3
~🧖🏾‍♂️	4
~🧖🏿‍♂️	5
🧖‍♀️	woman_in_steamy_room
~🧖🏻‍♀️	1
~🧖🏼‍♀️	2
~🧖🏽‍♀️	3
~🧖🏾‍♀️	4
~🧖🏿‍♀️	5
🧗	person_climbing
~🧗🏻	1
~🧗🏼	2
~🧗🏽	3
~🧗🏾	4
~🧗🏿	5
🧗‍♂️	man_climbing
~🧗🏻‍♂️	1
~🧗🏼‍♂️	2
~🧗🏽‍♂️	3
~🧗🏾‍♂️	4
~🧗🏿‍♂️	5
🧗‍♀️	woman_climbing
~🧗🏻‍♀️	1
~🧗🏼‍♀️	2
~🧗🏽‍♀️	3
~🧗🏾‍♀️	4
~🧗🏿‍♀️	5
🤺	fencer person_fencing
🏇	horse_racing
~🏇🏻	1
~🏇🏼	2
~🏇🏽	3
~🏇🏾	4
~🏇🏿	5
⛷️	skier
🏂	snowboarder
~🏂🏻	1
~🏂🏼	2
~🏂🏽	3
~🏂🏾	4
~🏂🏿	5
🏌️	golfer
~🏌🏻	1
~🏌🏼	2
~🏌🏽	3
~🏌🏾	4
~🏌🏿	5
🏌️‍♂️	man-golfing golfing_man
~🏌🏻‍♂️	1
~🏌🏼‍♂️	2
~🏌🏽‍♂️	3
~🏌🏾‍♂️	4
~🏌🏿‍♂️	5
🏌️‍♀️	woman-golfing golfing_woman
~🏌🏻‍♀️	1
~🏌🏼‍♀️	2
~🏌🏽‍♀️	3
~🏌🏾‍♀️	4
~🏌🏿‍♀️	5
🏄	surfer
~🏄🏻	1
~🏄🏼	2
~🏄🏽	3
~🏄🏾	4
~🏄🏿	5
🏄‍♂️	man-surfing surfing_man
~🏄🏻‍♂️	1
~🏄🏼‍♂️	2
~🏄🏽‍♂️	3
~🏄🏾‍♂️	4
~🏄🏿‍♂️	5
🏄‍♀️	woman-surfing surfing_woman
~🏄🏻‍♀️	1
~🏄🏼‍♀️	2
~🏄🏽‍♀️	3
~🏄🏾‍♀️	4
~🏄🏿‍♀️	5
🚣	rowboat
~🚣🏻	1
~🚣🏼	2
~🚣🏽	3
~🚣🏾	4
~🚣🏿	5
🚣‍♂️	man-rowing-boat rowing_man
~🚣🏻‍♂️	1
~🚣🏼‍♂️	2
~🚣🏽‍♂️	3
~🚣🏾‍♂️	4
~🚣🏿‍♂️	5
🚣‍♀️	woman-rowing-boat rowing_woman
~🚣🏻‍♀️	1
~🚣🏼‍♀️	2
~🚣🏽‍♀️	3
~🚣🏾‍♀️	4
~🚣🏿‍♀️	5
🏊	swimmer
~🏊🏻	1
~🏊🏼	2
~🏊🏽	3
~🏊🏾	4
~🏊🏿	5
🏊‍♂️	man-swimming swimming_man
~🏊🏻‍♂️	1
~🏊🏼‍♂️	2
~🏊🏽‍♂️	3
~🏊🏾‍♂️	4
~🏊🏿‍♂️	5
🏊‍♀️	woman-swimming swimming_woman
~🏊🏻‍♀️	1
~🏊🏼‍♀️	2
~🏊🏽‍♀️	3
~🏊🏾‍♀️	4
~🏊🏿‍♀️	5
⛹️	person_with_ball
~⛹🏻	1
~⛹🏼	2
~⛹🏽	3
~⛹🏾	4
~⛹🏿	5
⛹️‍♂️	man-bouncing-ball basketball_man
~⛹🏻‍♂️	1
~⛹🏼‍♂️	2
~⛹🏽‍♂️	3
~⛹🏾‍♂️	4
~⛹🏿‍♂️	5
⛹️‍♀️	woman-bouncing-ball basketball_woman
~⛹🏻‍♀️	1
~⛹🏼‍♀️	2
~⛹🏽‍♀️	3
~⛹🏾‍♀️	4
~⛹🏿‍♀️	5
🏋️	weight_lifter
~🏋🏻	1
~🏋🏼	2
~🏋🏽	3
~🏋🏾	4
~🏋🏿	5
🏋️‍♂️	man-lifting-weights weight_lifting_man
~🏋🏻‍♂️	1
~🏋🏼‍♂️	2
~🏋🏽‍♂️	3
~🏋🏾‍♂️	4
~🏋🏿‍♂️	5
🏋️‍♀️	woman-lifting-weights weight_lifting_woman
~🏋🏻‍♀️	1
~🏋🏼‍♀️	2
~🏋🏽‍♀️	3
~🏋🏾‍♀️	4
~🏋🏿‍♀️	5
🚴	bicyclist
~🚴🏻	1
~🚴🏼	2
~🚴🏽	3
~🚴🏾	4
~🚴🏿	5
🚴‍♂️	man-biking biking_man
~🚴🏻‍♂️	1
~🚴🏼‍♂️	2
~🚴🏽‍♂️	3
~🚴🏾‍♂️	4
~🚴🏿‍♂️	5
🚴‍♀️	woman-biking biking_woman
~🚴🏻‍♀️	1
~🚴🏼‍♀️	2
~🚴🏽‍♀️	3
~🚴🏾‍♀️	4
~🚴🏿‍♀️	5
🚵	mountain_bicyclist
~🚵🏻	1
~🚵🏼	2
~🚵🏽	3
~🚵🏾	4
~🚵🏿	5
🚵‍♂️	man-mountain-biking mountain_biking_man
~🚵🏻‍♂️	1
~🚵🏼‍♂️	2
~🚵🏽‍♂️	3
~🚵🏾‍♂️	4
~🚵🏿‍♂️	5
🚵‍♀️	woman-mountain-biking mountain_biking_woman
~🚵🏻‍♀️	1
~🚵🏼‍♀️	2
~🚵🏽‍♀️	3
~🚵🏾‍♀️	4
~🚵🏿‍♀️	5
🤸	person_doing_cartwheel
~🤸🏻	1
~🤸🏼	2
~🤸🏽	3
~🤸🏾	4
~🤸🏿	5
🤸‍♂️	man-cartwheeling man_cartwheeling
~🤸🏻‍♂️	1
~🤸🏼‍♂️	2
~🤸🏽‍♂️	3
~🤸🏾‍♂️	4
~🤸🏿‍♂️	5
🤸‍♀️	woman-cartwheeling woman_cartwheeling
~🤸🏻‍♀️	1
~🤸🏼‍♀️	2
~🤸🏽‍♀️	3
~🤸🏾‍♀️	4
~🤸🏿‍♀️	5
🤼	wrestlers
🤼‍♂️	man-wrestling men_wrestling
🤼‍♀️	woman-wrestling women_wrestling
🤽	water_polo
~🤽🏻	1
~🤽🏼	2
~🤽🏽	3
~🤽🏾	4
~🤽🏿	5
🤽‍♂️	man-playing-water-polo man_playing_water_polo
~🤽🏻‍♂️	1
~🤽🏼‍♂️	2
~🤽🏽‍♂️	3
~🤽🏾‍♂️	4
~🤽🏿‍♂️	5
🤽‍♀️	woman-playing-water-polo woman_playing_water_polo
~🤽🏻‍♀️	1
~🤽🏼‍♀️	2
~🤽🏽‍♀️	3
~🤽🏾‍♀️	4
~🤽🏿‍♀️	5
🤾	handball
~🤾🏻	1
~🤾🏼	2
~🤾🏽	3
~🤾🏾	4
~🤾🏿	5
🤾‍♂️	man-playing-handball man_playing_handball
~🤾🏻‍♂️	1
~🤾🏼‍♂️	2
~🤾🏽‍♂️	3
~🤾🏾‍♂️	4
~🤾🏿‍♂️	5
🤾‍♀️	woman-playing-handball woman_playing_handball
~🤾🏻‍♀️	1
~🤾🏼‍♀️	2
~🤾🏽‍♀️	3
~🤾🏾‍♀️	4
~🤾🏿‍♀️	5
🤹	juggling
~🤹🏻	1
~🤹🏼	2
~🤹🏽	3
~🤹🏾	4
~🤹🏿	5
🤹‍♂️	man-juggling man_juggling
~🤹🏻‍♂️	1
~🤹🏼‍♂️	2
~🤹🏽‍♂️	3
~🤹🏾‍♂️	4
~🤹🏿‍♂️	5
🤹‍♀️	woman-juggling woman_juggling
~🤹🏻‍♀️	1
~🤹🏼‍♀️	2
~🤹🏽‍♀️	3
~🤹🏾‍♀️	4
~🤹🏿‍♀️	5
🧘	person_in_lotus_position
~🧘🏻	1
~🧘🏼	2
~🧘🏽	3
~🧘🏾	4
~🧘🏿	5
🧘‍♂️	man_in_lotus_position
~🧘🏻‍♂️	1
~🧘🏼‍♂️	2
~🧘🏽‍♂️	3
~🧘🏾‍♂️	4
~🧘🏿‍♂️	5
🧘‍♀️	woman_in_lotus_position
~🧘🏻‍♀️	1
~🧘🏼‍♀️	2
~🧘🏽‍♀️	3
~🧘🏾‍♀️	4
~🧘🏿‍♀️	5
🛀	bath
~🛀🏻	1
~🛀🏼	2
~🛀🏽	3
~🛀🏾	4
~🛀🏿	5
🛌	sleeping_accommodation sleeping_bed
~🛌🏻	=sleeping_accommodation_light_skin_tone
~🛌🏼	=sleeping_accommodation_medium_light_skin_tone
~🛌🏽	=sleeping_accommodation_medium_skin_tone
~🛌🏾	=sleeping_accommodation_medium_dark_skin_tone
~🛌🏿	=sleeping_accommodation_dark_skin_tone
🧑‍🤝‍🧑	people_holding_hands
~🧑🏻‍🤝‍🧑🏻	11
~🧑🏻‍🤝‍🧑🏼	12
~🧑🏻‍🤝‍🧑🏽	13
~🧑🏻‍🤝‍🧑🏾	14
~🧑🏻‍🤝‍🧑🏿	15
~🧑🏼‍🤝‍🧑🏻	21
~🧑🏼‍🤝‍🧑🏼	22
~🧑🏼‍🤝‍🧑🏽	23
~🧑🏼‍🤝‍🧑🏾	24
~🧑🏼‍🤝‍🧑🏿	25
~🧑🏽‍🤝‍🧑🏻	31
~🧑🏽‍🤝‍🧑🏼	32
~🧑🏽‍🤝‍🧑🏽	33
~🧑🏽‍🤝‍🧑🏾	34
~🧑🏽‍🤝‍🧑🏿	35
~🧑🏾‍🤝‍🧑🏻	41
~🧑🏾‍🤝‍🧑🏼	42
~🧑🏾‍🤝‍🧑🏽	43
~🧑🏾‍🤝‍🧑🏾	44
~🧑🏾‍🤝‍🧑🏿	45
~🧑🏿‍🤝‍🧑🏻	51
~🧑🏿‍🤝‍🧑🏼	52
~🧑🏿‍🤝‍🧑🏽	53
~🧑🏿‍🤝‍🧑🏾	54
~🧑🏿‍🤝‍🧑🏿	55
👭	two_women_holding_hands women_holding_hands
~👭🏻	1
~👩🏻‍🤝‍👩🏼	12
~👩🏻‍🤝‍👩🏽	13
~👩🏻‍🤝‍👩🏾	14
~👩🏻‍🤝‍👩🏿	15
~👭🏼	2
~👩🏼‍🤝‍👩🏻	21
~👩🏼‍🤝‍👩🏽	23
~👩🏼‍🤝‍👩🏾	24
~👩🏼‍🤝‍👩🏿	25
~👭🏽	3
~👩🏽‍🤝‍👩🏻	31
~👩🏽‍🤝‍👩🏼	32
~👩🏽‍🤝‍👩🏾	34
~👩🏽‍🤝‍👩🏿	35
~👭🏾	4
~👩🏾‍🤝‍👩🏻	41
~👩🏾‍🤝‍👩🏼	42
~👩🏾‍🤝‍👩🏽	43
~👩🏾‍🤝‍👩🏿	45
~👭🏿	5
~👩🏿‍🤝‍👩🏻	51
~👩🏿‍🤝‍👩🏼	52
~👩🏿‍🤝‍👩🏽	53
~👩🏿‍🤝‍👩🏾	54
👫	man_and_woman_holding_hands woman_and_man_holding_hands couple
~👫🏻	1
~👩🏻‍🤝‍👨🏼	12
~👩🏻‍🤝‍👨🏽	13
~👩🏻‍🤝‍👨🏾	14
~👩🏻‍🤝‍👨🏿	15
~👫🏼	2
~👩🏼‍🤝‍👨🏻	21
~👩🏼‍🤝‍👨🏽	23
~👩🏼‍🤝‍👨🏾	24
~👩🏼‍🤝‍👨🏿	25
~👫🏽	3
~👩🏽‍🤝‍👨🏻	31
~👩🏽‍🤝‍👨🏼	32
~👩🏽‍🤝‍👨🏾	34
~👩🏽‍🤝‍👨🏿	35
~👫🏾	4
~👩🏾‍🤝‍👨🏻	41
~👩🏾‍🤝‍👨🏼	42
~👩🏾‍🤝‍👨🏽	43
~👩🏾‍🤝‍👨🏿	45
~👫🏿	5
~👩🏿‍🤝‍👨🏻	51
~👩🏿‍🤝‍👨🏼	52
~👩🏿‍🤝‍👨🏽	53
~👩🏿‍🤝‍👨🏾	54
👬	two_men_holding_hands men_holding_hands
~👬🏻	1
~👨🏻‍🤝‍👨🏼	12
~👨🏻‍🤝‍👨🏽	13
~👨🏻‍🤝‍👨🏾	14
~👨🏻‍🤝‍👨🏿	15
~👬🏼	2
~👨🏼‍🤝‍👨🏻	21
~👨🏼‍🤝‍👨🏽	23
~👨🏼‍🤝‍👨🏾	24
~👨🏼‍🤝‍👨🏿	25
~👬🏽	3
~👨🏽‍🤝‍👨🏻	31
~👨🏽‍🤝‍👨🏼	32
~👨🏽‍🤝‍👨🏾	34
~👨🏽‍🤝‍👨🏿	35
~👬🏾	4
~👨🏾‍🤝‍👨🏻	41
~👨🏾‍🤝‍👨🏼	42
~👨🏾‍🤝‍👨🏽	43
~👨🏾‍🤝‍👨🏿	45
~👬🏿	5
~👨🏿‍🤝‍👨🏻	51
~👨🏿‍🤝‍👨🏼	52
~👨🏿‍🤝‍👨🏽	53
~👨🏿‍🤝‍👨🏾	54
💏	couplekiss
👩‍❤️‍💋‍👨	woman-kiss-man couplekiss_man_woman
👨‍❤️‍💋‍👨	man-kiss-man couplekiss_man_man
👩‍❤️‍💋‍👩	woman-kiss-woman couplekiss_woman_woman
💑	couple_with_heart
👩‍❤️‍👨	woman-heart-man couple_with_heart_woman_man
👨‍❤️‍👨	man-heart-man couple_with_heart_man_man
👩‍❤️‍👩	woman-heart-woman couple_with_heart_woman_woman
👪	family
👨‍👩‍👦	man-woman-boy family_man_woman_boy
👨‍👩‍👧	man-woman-girl family_man_woman_girl
👨‍👩‍👧‍👦	man-woman-girl-boy family_man_woman_girl_boy
👨‍👩‍👦‍👦	man-woman-boy-boy family_man_woman_boy_boy
👨‍👩‍👧‍👧	man-woman-girl-girl family_man_woman_girl_girl
👨‍👨‍👦	man-man-boy family_man_man_boy
👨‍👨‍👧	man-man-girl family_man_man_girl
👨‍👨‍👧‍👦	man-man-girl-boy family_man_man_girl_boy
👨‍👨‍👦‍👦	man-man-boy-boy family_man_man_boy_boy
👨‍👨‍👧‍👧	man-man-girl-girl family_man_man_girl_girl
👩‍👩‍👦	woman-woman-boy family_woman_woman_boy
👩‍👩‍👧	woman-woman-girl family_woman_woman_girl
👩‍👩‍👧‍👦	woman-woman-girl-boy family_woman_woman_girl_boy
👩‍👩‍👦‍👦	woman-woman-boy-boy family_woman_woman_boy_boy
👩‍👩‍👧‍👧	woman-woman-girl-girl family_woman_woman_girl_girl
👨‍👦	man-boy family_man_boy
👨‍👦‍👦	man-boy-boy family_man_boy_boy
👨‍👧	man-girl family_man_girl
👨‍👧‍👦	man-girl-boy family_man_girl_boy
👨‍👧‍👧	man-girl-girl family_man_girl_girl
👩‍👦	woman-boy family_woman_boy
👩‍👦‍👦	woman-boy-boy family_woman_boy_boy
👩‍👧	woman-girl family_woman_girl
👩‍👧‍👦	woman-girl-boy family_woman_girl_boy
👩‍👧‍👧	woman-girl-girl family_woman_girl_girl
🗣️	speaking_head_in_silhouette speaking_head
👤	bust_in_silhouette
👥	busts_in_silhouette
🫂	people_hugging
👣	footprints
@animals-nature
🐵	monkey_face
🐒	monkey
🦍	gorilla
🦧	orangutan
🐶	dog
🐕	dog2
🦮	guide_dog
🐕‍🦺	service_dog
🐩	poodle
🐺	wolf
🦊	fox_face
🦝	raccoon
🐱	cat
🐈	cat2
🐈‍⬛	black_cat
🦁	lion_face lion
🐯	tiger
🐅	tiger2
🐆	leopard
🐴	horse
🐎	racehorse
🦄	unicorn_face unicorn
🦓	zebra_face
🦌	deer
🦬	bison
🐮	cow
🐂	ox
🐃	water_buffalo
🐄	cow2
🐷	pig
🐖	pig2
🐗	boar
🐽	pig_nose
🐏	ram
🐑	sheep
🐐	goat
🐪	dromedary_camel
🐫	camel
🦙	llama
🦒	giraffe_face
🐘	elephant
🦣	mammoth
🦏	rhinoceros
🦛	hippopotamus
🐭	mouse
🐁	mouse2
🐀	rat
🐹	hamster
🐰	rabbit
🐇	rabbit2
🐿️	chipmunk
🦫	beaver
🦔	hedgehog
🦇	bat
🐻	bear
🐻‍❄️	polar_bear
🐨	koala
🐼	panda_face
🦥	sloth
🦦	otter
🦨	skunk
🦘	kangaroo
🦡	badger
🐾	feet paw_prints
🦃	turkey
🐔	chicken
🐓	rooster
🐣	hatching_chick
🐤	baby_chick
🐥	hatched_chick
🐦	bird
🐧	penguin
🕊️	dove_of_peace dove
🦅	eagle
🦆	duck
🦢	swan
🦉	owl
🦤	dodo
🪶	feather
🦩	flamingo
🦚	peacock
🦜	parrot
🐸	frog
🐊	crocodile
🐢	turtle
🦎	lizard
🐍	snake
🐲	dragon_face
🐉	dragon
🦕	sauropod
🦖	t-rex
🐳	whale
🐋	whale2
🐬	dolphin flipper
🦭	seal
🐟	fish
🐠	tropical_fish
🐡	blowfish
🦈	shark
🐙	octopus
🐚	shell
🐌	snail
🦋	butterfly
🐛	bug
🐜	ant
🐝	bee honeybee
🪲	beetle
🐞	ladybug lady_beetle
🦗	cricket
🪳	cockroach
🕷️	spider
🕸️	spider_web
🦂	scorpion
🦟	mosquito
🪰	fly
🪱	worm
🦠	microbe
💐	bouquet
🌸	cherry_blossom
💮	white_flower
🏵️	rosette
🌹	rose
🥀	wilted_flower
🌺	hibiscus
🌻	sunflower
🌼	blossom
🌷	tulip
🌱	seedling
🪴	potted_plant
🌲	evergreen_tree
🌳	deciduous_tree
🌴	palm_tree
🌵	cactus
🌾	ear_of_rice
🌿	herb
☘️	shamrock
🍀	four_leaf_clover
🍁	maple_leaf
🍂	fallen_leaf
🍃	leaves
@food-drink
🍇	grapes
🍈	melon
🍉	watermelon
🍊	tangerine mandarin orange
🍋	lemon
🍌	banana
🍍	pineapple
🥭	mango
🍎	apple
🍏	green_apple
🍐	pear
🍑	peach
🍒	cherries
🍓	strawberry
🫐	blueberries
🥝	kiwifruit kiwi_fruit
🍅	tomato
🫒	olive
🥥	coconut
🥑	avocado
🍆	eggplant
🥔	potato
🥕	carrot
🌽	corn
🌶️	hot_pepper
🫑	bell_pepper
🥒	cucumber
🥬	leafy_green
🥦	broccoli
🧄	garlic
🧅	onion
🍄	mushroom
🥜	peanuts
🌰	chestnut
🍞	bread
🥐	croissant
🥖	baguette_bread
🫓	flatbread
🥨	pretzel
🥯	bagel
🥞	pancakes
🧇	waffle
🧀	cheese_wedge cheese
🍖	meat_on_bone
🍗	poultry_leg
🥩	cut_of_meat
🥓	bacon
🍔	hamburger
🍟	fries
🍕	pizza
🌭	hotdog
🥪	sandwich
🌮	taco
🌯	burrito
🫔	tamale
🥙	stuffed_flatbread
🧆	falafel
🥚	egg
🍳	fried_egg cooking
🥘	shallow_pan_of_food
🍲	stew
🫕	fondue
🥣	bowl_with_spoon
🥗	green_salad
🍿	popcorn
🧈	butter
🧂	salt
🥫	canned_food
🍱	bento
🍘	rice_cracker
🍙	rice_ball
🍚	rice
🍛	curry
🍜	ramen
🍝	spaghetti
🍠	sweet_potato
🍢	oden
🍣	sushi
🍤	fried_shrimp
🍥	fish_cake
🥮	moon_cake
🍡	dango
🥟	dumpling
🥠	fortune_cookie
🥡	takeout_box
🦀	crab
🦞	lobster
🦐	shrimp
🦑	squid
🦪	oyster
🍦	icecream
🍧	shaved_ice
🍨	ice_cream
🍩	doughnut
🍪	cookie
🎂	birthday
🍰	cake
🧁	cupcake
🥧	pie
🍫	chocolate_bar
🍬	candy
🍭	lollipop
🍮	custard
🍯	honey_pot
🍼	baby_bottle
🥛	glass_of_milk milk_glass
☕	coffee
🫖	teapot
🍵	tea
🍶	sake
🍾	champagne
🍷	wine_glass
🍸	cocktail
🍹	tropical_drink
🍺	beer
🍻	beers
🥂	clinking_glasses
🥃	tumbler_glass
🥤	cup_with_straw
🧋	bubble_tea
🧃	beverage_box
🧉	mate_drink
🧊	ice_cube
🥢	chopsticks
🍽️	knife_fork_plate plate_with_cutlery
🍴	fork_and_knife
🥄	spoon
🔪	hocho knife
🏺	amphora
@activities
🎃	jack_o_lantern
🎄	christmas_tree
🎆	fireworks
🎇	sparkler
🧨	firecracker
✨	sparkles
🎈	balloon
🎉	tada
🎊	confetti_ball
🎋	tanabata_tree
🎍	bamboo
🎎	dolls
🎏	flags
🎐	wind_chime
🎑	rice_scene
🧧	red_envelope
🎀	ribbon
🎁	gift
🎗️	reminder_ribbon
🎟️	admission_tickets tickets
🎫	ticket
🎖️	medal medal_military
🏆	trophy
🏅	sports_medal medal_sports
🥇	first_place_medal 1st_place_medal
🥈	second_place_medal 2nd_place_medal
🥉	third_place_medal 3rd_place_medal
⚽	soccer
⚾	baseball
🥎	softball
🏀	basketball
🏐	volleyball
🏈	football
🏉	rugby_football
🎾	tennis
🥏	flying_disc
🎳	bowling
🏏	cricket_bat_and_ball
🏑	field_hockey_stick_and_ball field_hockey
🏒	ice_hockey_stick_and_puck ice_hockey
🥍	lacrosse
🏓	table_tennis_paddle_and_ball ping_pong
🏸	badminton_racquet_and_shuttlecock badminton
🥊	boxing_glove
🥋	martial_arts_uniform
🥅	goal_net
⛳	golf
⛸️	ice_skate
🎣	fishing_pole_and_fish
🤿	diving_mask
🎽	running_shirt_with_sash
🎿	ski
🛷	sled
🥌	curling_stone
🎯	dart
🪀	yo-yo
🪁	kite
🎱	8ball
🔮	crystal_ball
🪄	magic_wand
🧿	nazar_amulet
🎮	video_game
🕹️	joystick
🎰	slot_machine
🎲	game_die
🧩	jigsaw
🧸	teddy_bear
🪅	pinata
🪆	nesting_dolls
♠️	spades
♥️	hearts
♦️	diamonds
♣️	clubs
♟️	chess_pawn
🃏	black_joker
🀄	mahjong
🎴	flower_playing_cards
🎭	performing_arts
🖼️	frame_with_picture framed_picture
🎨	art
🧵	thread
🪡	sewing_needle
🧶	yarn
🪢	knot
@travel-places
🌍	earth_africa
🌎	earth_americas
🌏	earth_asia
🌐	globe_with_meridians
🗺️	world_map
🗾	japan
🧭	compass
🏔️	snow_capped_mountain mountain_snow
⛰️	mountain
🌋	volcano
🗻	mount_fuji
🏕️	camping
🏖️	beach_with_umbrella beach_umbrella
🏜️	desert
🏝️	desert_island
🏞️	national_park
🏟️	stadium
🏛️	classical_building
🏗️	building_construction
🧱	bricks
🪨	rock
🪵	wood
🛖	hut
🏘️	house_buildings houses
🏚️	derelict_house_building derelict_house
🏠	house
🏡	house_with_garden
🏢	office
🏣	post_office
🏤	european_post_office
🏥	hospital
🏦	bank
🏨	hotel
🏩	love_hotel
🏪	convenience_store
🏫	school
🏬	department_store
🏭	factory
🏯	japanese_castle
🏰	european_castle
💒	wedding
🗼	tokyo_tower
🗽	statue_of_liberty
⛪	church
🕌	mosque
🛕	hindu_temple
🕍	synagogue
⛩️	shinto_shrine
🕋	kaaba
⛲	fountain
⛺	tent
🌁	foggy
🌃	night_with_stars
🏙️	cityscape
🌄	sunrise_over_mountains
🌅	sunrise
🌆	city_sunset
🌇	city_sunrise
🌉	bridge_at_night
♨️	hotsprings
🎠	carousel_horse
🎡	ferris_wheel
🎢	roller_coaster
💈	barber
🎪	circus_tent
🚂	steam_locomotive
🚃	railway_car
🚄	bullettrain_side
🚅	bullettrain_front
🚆	train2
🚇	metro
🚈	light_rail
🚉	station
🚊	tram
🚝	monorail
🚞	mountain_railway
🚋	train
🚌	bus
🚍	oncoming_bus
🚎	trolleybus
🚐	minibus
🚑	ambulance
🚒	fire_engine
🚓	police_car
🚔	oncoming_police_car
🚕	taxi
🚖	oncoming_taxi
🚗	car red_car
🚘	oncoming_automobile
🚙	blue_car
🛻	pickup_truck
🚚	truck
🚛	articulated_lorry
🚜	tractor
🏎️	racing_car
🏍️	racing_motorcycle motorcycle
🛵	motor_scooter
🦽	manual_wheelchair
🦼	motorized_wheelchair
🛺	auto_rickshaw
🚲	bike
🛴	scooter kick_scooter
🛹	skateboard
🛼	roller_skate
🚏	busstop
🛣️	motorway
🛤️	railway_track
🛢️	oil_drum
⛽	fuelpump
🚨	rotating_light
🚥	traffic_light
🚦	vertical_traffic_light
🛑	octagonal_sign stop_sign
🚧	construction
⚓	anchor
⛵	boat sailboat
🛶	canoe
🚤	speedboat
🛳️	passenger_ship
⛴️	ferry
🛥️	motor_boat
🚢	ship
✈️	airplane
🛩️	small_airplane
🛫	airplane_departure flight_departure
🛬	airplane_arriving flight_arrival
🪂	parachute
💺	seat
🚁	helicopter
🚟	suspension_railway
🚠	mountain_cableway
🚡	aerial_tramway
🛰️	satellite artificial_satellite
🚀	rocket
🛸	flying_saucer
🛎️	bellhop_bell
🧳	luggage
⌛	hourglass
⏳	hourglass_flowing_sand
⌚	watch
⏰	alarm_clock
⏱️	stopwatch
⏲️	timer_clock
🕰️	mantelpiece_clock
🕛	clock12
🕧	clock1230
🕐	clock1
🕜	clock130
🕑	clock2
🕝	clock230
🕒	clock3
🕞	clock330
🕓	clock4
🕟	clock430
🕔	clock5
🕠	clock530
🕕	clock6
🕡	clock630
🕖	clock7
🕢	clock730
🕗	clock8
🕣	clock830
🕘	clock9
🕤	clock930
🕙	clock10
🕥	clock1030
🕚	clock11
🕦	clock1130
🌑	new_moon
🌒	waxing_crescent_moon
🌓	first_quarter_moon
🌔	moon waxing_gibbous_moon
🌕	full_moon
🌖	waning_gibbous_moon
🌗	last_quarter_moon
🌘	waning_crescent_moon
🌙	crescent_moon
🌚	new_moon_with_face
🌛	first_quarter_moon_with_face
🌜	last_quarter_moon_with_face
🌡️	thermometer
☀️	sunny
🌝	full_moon_with_face
🌞	sun_with_face
🪐	ringed_planet
⭐	star
🌟	star2
🌠	stars
🌌	milky_way
☁️	cloud
⛅	partly_sunny
⛈️	thunder_cloud_and_rain cloud_with_lightning_and_rain
🌤️	mostly_sunny sun_small_cloud sun_behind_small_cloud
🌥️	barely_sunny sun_behind_cloud sun_behind_large_cloud
🌦️	partly_sunny_rain sun_behind_rain_cloud
🌧️	rain_cloud cloud_with_rain
🌨️	snow_cloud cloud_with_snow
🌩️	lightning lightning_cloud cloud_with_lightning
🌪️	tornado tornado_cloud
🌫️	fog
🌬️	wind_blowing_face wind_face
🌀	cyclone
🌈	rainbow
🌂	closed_umbrella
☂️	umbrella open_umbrella
☔	umbrella_with_rain_drops
⛱️	umbrella_on_ground parasol_on_ground
⚡	zap
❄️	snowflake
☃️	snowman snowman_with_snow
⛄	snowman_without_snow
☄️	comet
🔥	fire
💧	droplet
🌊	ocean
@objects
👓	eyeglasses
🕶️	dark_sunglasses
🥽	goggles
🥼	lab_coat
🦺	safety_vest
👔	necktie
👕	shirt tshirt
👖	jeans
🧣	scarf
🧤	gloves
🧥	coat
🧦	socks
👗	dress
👘	kimono
🥻	sari
🩱	one-piece_swimsuit
🩲	briefs
🩳	shorts
👙	bikini
👚	womans_clothes
👛	purse
👜	handbag
👝	pouch
🛍️	shopping_bags shopping
🎒	school_satchel
🩴	thong_sandal
👞	mans_shoe shoe
👟	athletic_shoe
🥾	hiking_boot
🥿	womans_flat_shoe
👠	high_heel
👡	sandal
🩰	ballet_shoes
👢	boot
👑	crown
👒	womans_hat
🎩	tophat
🎓	mortar_board
🧢	billed_cap
🪖	military_helmet
⛑️	helmet_with_white_cross rescue_worker_helmet
📿	prayer_beads
💄	lipstick
💍	ring
💎	gem
🔇	mute
🔈	speaker
🔉	sound
🔊	loud_sound
📢	loudspeaker
📣	mega
📯	postal_horn
🔔	bell
🔕	no_bell
🎼	musical_score
🎵	musical_note
🎶	notes
🎙️	studio_microphone
🎚️	level_slider
🎛️	control_knobs
🎤	microphone
🎧	headphones
📻	radio
🎷	saxophone
🪗	accordion
🎸	guitar
🎹	musical_keyboard
🎺	trumpet
🎻	violin
🪕	banjo
🥁	drum_with_drumsticks drum
🪘	long_drum
📱	iphone
📲	calling
☎️	phone telephone
📞	telephone_receiver
📟	pager
📠	fax
🔋	battery
🔌	electric_plug
💻	computer
🖥️	desktop_computer
🖨️	printer
⌨️	keyboard
🖱️	three_button_mouse computer_mouse
🖲️	trackball
💽	minidisc
💾	floppy_disk
💿	cd
📀	dvd
🧮	abacus
🎥	movie_camera
🎞️	film_frames film_strip
📽️	film_projector
🎬	clapper
📺	tv
📷	camera
📸	camera_with_flash camera_flash
📹	video_camera
📼	vhs
🔍	mag
🔎	mag_right
🕯️	candle
💡	bulb
🔦	flashlight
🏮	izakaya_lantern lantern
🪔	diya_lamp
📔	notebook_with_decorative_cover
📕	closed_book
📖	book open_book
📗	green_book
📘	blue_book
📙	orange_book
📚	books
📓	notebook
📒	ledger
📃	page_with_curl
📜	scroll
📄	page_facing_up
📰	newspaper
🗞️	rolled_up_newspaper newspaper_roll
📑	bookmark_tabs
🔖	bookmark
🏷️	label
💰	moneybag
🪙	coin
💴	yen
💵	dollar
💶	euro
💷	pound
💸	money_with_wings
💳	credit_card
🧾	receipt
💹	chart
✉️	email envelope
📧	e-mail
📨	incoming_envelope
📩	envelope_with_arrow
📤	outbox_tray
📥	inbox_tray
📦	package
📫	mailbox
📪	mailbox_closed
📬	mailbox_with_mail
📭	mailbox_with_no_mail
📮	postbox
🗳️	ballot_box_with_ballot ballot_box
✏️	pencil2
✒️	black_nib
🖋️	lower_left_fountain_pen fountain_pen
🖊️	lower_left_ballpoint_pen pen
🖌️	lower_left_paintbrush paintbrush
🖍️	lower_left_crayon crayon
📝	memo pencil
💼	briefcase
📁	file_folder
📂	open_file_folder
🗂️	card_index_dividers
📅	date
📆	calendar
🗒️	spiral_note_pad spiral_notepad
🗓️	spiral_calendar_pad spiral_calendar
📇	card_index
📈	chart_with_upwards_trend
📉	chart_with_downwards_trend
📊	bar_chart
📋	clipboard
📌	pushpin
📍	round_pushpin
📎	paperclip
🖇️	linked_paperclips paperclips
📏	straight_ruler
📐	triangular_ruler
✂️	scissors
🗃️	card_file_box
🗄️	file_cabinet
🗑️	wastebasket
🔒	lock
🔓	unlock
🔏	lock_with_ink_pen
🔐	closed_lock_with_key
🔑	key
🗝️	old_key
🔨	hammer
🪓	axe
⛏️	pick
⚒️	hammer_and_pick
🛠️	hammer_and_wrench
🗡️	dagger_knife dagger
⚔️	crossed_swords
🔫	gun
🪃	boomerang
🏹	bow_and_arrow
🛡️	shield
🪚	carpentry_saw
🔧	wrench
🪛	screwdriver
🔩	nut_and_bolt
⚙️	gear
🗜️	compression clamp
⚖️	scales balance_scale
🦯	probing_cane
🔗	link
⛓️	chains
🪝	hook
🧰	toolbox
🧲	magnet
🪜	ladder
⚗️	alembic
🧪	test_tube
🧫	petri_dish
🧬	dna
🔬	microscope
🔭	telescope
📡	satellite_antenna
💉	syringe
🩸	drop_of_blood
💊	pill
🩹	adhesive_bandage
🩺	stethoscope
🚪	door
🛗	elevator
🪞	mirror
🪟	window
🛏️	bed
🛋️	couch_and_lamp
🪑	chair
🚽	toilet
🪠	plunger
🚿	shower
🛁	bathtub
🪤	mouse_trap
🪒	razor
🧴	lotion_bottle
🧷	safety_pin
🧹	broom
🧺	basket
🧻	roll_of_paper
🪣	bucket
🧼	soap
🪥	toothbrush
🧽	sponge
🧯	fire_extinguisher
🛒	shopping_trolley shopping_cart
🚬	smoking
⚰️	coffin
🪦	headstone
⚱️	funeral_urn
🗿	moyai
🪧	placard
@symbols
🏧	atm
🚮	put_litter_in_its_place
🚰	potable_water
♿	wheelchair
🚹	mens
🚺	womens
🚻	restroom
🚼	baby_symbol
🚾	wc
🛂	passport_control
🛃	customs
🛄	baggage_claim
🛅	left_luggage
⚠️	warning
🚸	children_crossing
⛔	no_entry
🚫	no_entry_sign
🚳	no_bicycles
🚭	no_smoking
🚯	do_not_litter
🚱	non-potable_water
🚷	no_pedestrians
📵	no_mobile_phones
🔞	underage
☢️	radioactive_sign radioactive
☣️	biohazard_sign biohazard
⬆️	arrow_up
↗️	arrow_upper_right
➡️	arrow_right
↘️	arrow_lower_right
⬇️	arrow_down
↙️	arrow_lower_left
⬅️	arrow_left
↖️	arrow_upper_left
↕️	arrow_up_down
↔️	left_right_arrow
↩️	leftwards_arrow_with_hook
↪️	arrow_right_hook
⤴️	arrow_heading_up
⤵️	arrow_heading_down
🔃	arrows_clockwise
🔄	arrows_counterclockwise
🔙	back
🔚	end
🔛	on
🔜	soon
🔝	top
🛐	place_of_worship
⚛️	atom_symbol
🕉️	om_symbol om
✡️	star_of_david
☸️	wheel_of_dharma
☯️	yin_yang
✝️	latin_cross
☦️	orthodox_cross
☪️	star_and_crescent
☮️	peace_symbol
🕎	menorah_with_nine_branches menorah
🔯	six_pointed_star
♈	aries
♉	taurus
♊	gemini
♋	cancer
♌	leo
♍	virgo
♎	libra
♏	scorpius
♐	sagittarius
♑	capricorn
♒	aquarius
♓	pisces
⛎	ophiuchus
🔀	twisted_rightwards_arrows
🔁	repeat
🔂	repeat_one
▶️	arrow_forward
⏩	fast_forward
⏭️	black_right_pointing_double_triangle_with_vertical_bar next_track_button
⏯️	black_right_pointing_triangle_with_double_vertical_bar play_or_pause_button
◀️	arrow_backward
⏪	rewind
⏮️	black_left_pointing_double_triangle_with_vertical_bar previous_track_button
🔼	arrow_up_small
⏫	arrow_double_up
🔽	arrow_down_small
⏬	arrow_double_down
⏸️	double_vertical_bar pause_button
⏹️	black_square_for_stop stop_button
⏺️	black_circle_for_record record_button
⏏️	eject
🎦	cinema
🔅	low_brightness
🔆	high_brightness
📶	signal_strength
📳	vibration_mode
📴	mobile_phone_off
♀️	female_sign
♂️	male_sign
⚧️	transgender_symbol
✖️	heavy_multiplication_x
➕	heavy_plus_sign
➖	heavy_minus_sign
➗	heavy_division_sign
♾️	infinity
‼️	bangbang
⁉️	interrobang
❓	question
❔	grey_question
❕	grey_exclamation
❗	exclamation heavy_exclamation_mark
〰️	wavy_dash
💱	currency_exchange
💲	heavy_dollar_sign
⚕️	medical_symbol staff_of_aesculapius
♻️	recycle
⚜️	fleur_de_lis
🔱	trident
📛	name_badge
🔰	beginner
⭕	o
✅	white_check_mark
☑️	ballot_box_with_check
✔️	heavy_check_mark
❌	x
❎	negative_squared_cross_mark
➰	curly_loop
➿	loop
〽️	part_alternation_mark
✳️	eight_spoked_asterisk
✴️	eight_pointed_black_star
❇️	sparkle
©️	copyright
®️	registered
™️	tm
#️⃣	hash
*️⃣	keycap_star asterisk
0️⃣	zero
1️⃣	one
2️⃣	two
3️⃣	three
4️⃣	four
5️⃣	five
6️⃣	six
7️⃣	seven
8️⃣	eight
9️⃣	nine
🔟	keycap_ten
🔠	capital_abcd
🔡	abcd
🔢	1234
🔣	symbols
🔤	abc
🅰️	a
🆎	ab
🅱️	b
🆑	cl
🆒	cool
🆓	free
ℹ️	information_source
🆔	id
Ⓜ️	m
🆕	new
🆖	ng
🅾️	o2
🆗	ok
🅿️	parking
🆘	sos
🆙	up
🆚	vs
🈁	koko
🈂️	sa
🈷️	u6708
🈶	u6709
🈯	u6307
🉐	ideograph_advantage
🈹	u5272
🈚	u7121
🈲	u7981
🉑	accept
🈸	u7533
🈴	u5408
🈳	u7a7a
㊗️	congratulations
㊙️	secret
🈺	u55b6
🈵	u6e80
🔴	red_circle
🟠	large_orange_circle
🟡	large_yellow_circle
🟢	large_green_circle
🔵	large_blue_circle
🟣	large_purple_circle
🟤	large_brown_circle
⚫	black_circle
⚪	white_circle
🟥	large_red_square
🟧	large_orange_square
🟨	large_yellow_square
🟩	large_green_square
🟦	large_blue_square
🟪	large_purple_square
🟫	large_brown_square
⬛	black_large_square
⬜	white_large_square
◼️	black_medium_square
◻️	white_medium_square
◾	black_medium_small_square
◽	white_medium_small_square
▪️	black_small_square
▫️	white_small_square
🔶	large_orange_diamond
🔷	large_blue_diamond
🔸	small_orange_diamond
🔹	small_blue_diamond
🔺	small_red_triangle
🔻	small_red_triangle_down
💠	diamond_shape_with_a_dot_inside
🔘	radio_button
🔳	white_square_button
🔲	black_square_button
@flags
🏁	checkered_flag
🚩	triangular_flag_on_post
🎌	crossed_flags
🏴	waving_black_flag black_flag
🏳️	waving_white_flag white_flag
🏳️‍🌈	rainbow-flag rainbow_flag
🏳️‍⚧️	transgender_flag
🏴‍☠️	pirate_flag
🇦🇨	flag-ac
🇦🇩	flag-ad andorra
🇦🇪	flag-ae united_arab_emirates
🇦🇫	flag-af afghanistan
🇦🇬	flag-ag antigua_barbuda
🇦🇮	flag-ai anguilla
🇦🇱	flag-al albania
🇦🇲	flag-am armenia
🇦🇴	flag-ao angola
🇦🇶	flag-aq antarctica
🇦🇷	flag-ar argentina
🇦🇸	flag-as american_samoa
🇦🇹	flag-at austria
🇦🇺	flag-au australia
🇦🇼	flag-aw aruba
🇦🇽	flag-ax aland_islands
🇦🇿	flag-az azerbaijan
🇧🇦	flag-ba bosnia_herzegovina
🇧🇧	flag-bb barbados
🇧🇩	flag-bd bangladesh
🇧🇪	flag-be belgium
🇧🇫	flag-bf burkina_faso
🇧🇬	flag-bg bulgaria
🇧🇭	flag-bh bahrain
🇧🇮	flag-bi burundi
🇧🇯	flag-bj benin
🇧🇱	flag-bl st_barthelemy
🇧🇲	flag-bm bermuda
🇧🇳	flag-bn brunei
🇧🇴	flag-bo bolivia
🇧🇶	flag-bq caribbean_netherlands
🇧🇷	flag-br brazil
🇧🇸	flag-bs bahamas
🇧🇹	flag-bt bhutan
🇧🇻	flag-bv
🇧🇼	flag-bw botswana
🇧🇾	flag-by belarus
🇧🇿	flag-bz belize
🇨🇦	flag-ca ca canada
🇨🇨	flag-cc cocos_islands
🇨🇩	flag-cd congo_kinshasa
🇨🇫	flag-cf central_african_republic
🇨🇬	flag-cg congo_brazzaville
🇨🇭	flag-ch switzerland
🇨🇮	flag-ci cote_divoire
🇨🇰	flag-ck cook_islands
🇨🇱	flag-cl chile
🇨🇲	flag-cm cameroon
🇨🇳	cn flag-cn
🇨🇴	flag-co colombia
🇨🇵	flag-cp
🇨🇷	flag-cr costa_rica
🇨🇺	flag-cu cuba
🇨🇻	flag-cv cape_verde
🇨🇼	flag-cw curacao
🇨🇽	flag-cx christmas_island
🇨🇾	flag-cy cyprus
🇨🇿	flag-cz czech_republic
🇩🇪	de flag-de
🇩🇬	flag-dg
🇩🇯	flag-dj djibouti
🇩🇰	flag-dk denmark
🇩🇲	flag-dm dominica
🇩🇴	flag-do dominican_republic
🇩🇿	flag-dz algeria
🇪🇦	flag-ea
🇪🇨	flag-ec ecuador
🇪🇪	flag-ee estonia
🇪🇬	flag-eg egypt
🇪🇭	flag-eh western_sahara
🇪🇷	flag-er eritrea
🇪🇸	es flag-es
🇪🇹	flag-et ethiopia
🇪🇺	flag-eu eu european_union
🇫🇮	flag-fi finland
🇫🇯	flag-fj fiji
🇫🇰	flag-fk falkland_islands
🇫🇲	flag-fm micronesia
🇫🇴	flag-fo faroe_islands
🇫🇷	fr flag-fr
🇬🇦	flag-ga gabon
🇬🇧	gb uk flag-gb
🇬🇩	flag-gd grenada
🇬🇪	flag-ge georgia
🇬🇫	flag-gf french_guiana
🇬🇬	flag-gg guernsey
🇬🇭	flag-gh ghana
🇬🇮	flag-gi gibraltar
🇬🇱	flag-gl greenland
🇬🇲	flag-gm gambia
🇬🇳	flag-gn guinea
🇬🇵	flag-gp guadeloupe
🇬🇶	flag-gq equatorial_guinea
🇬🇷	flag-gr greece
🇬🇸	flag-gs south_georgia_south_sandwich_islands
🇬🇹	flag-gt guatemala
🇬🇺	flag-gu guam
🇬🇼	flag-gw guinea_bissau
🇬🇾	flag-gy guyana
🇭🇰	flag-hk hong_kong
🇭🇲	flag-hm
🇭🇳	flag-hn honduras
🇭🇷	flag-hr croatia
🇭🇹	flag-ht haiti
🇭🇺	flag-hu hungary
🇮🇨	flag-ic canary_islands
🇮🇩	flag-id indonesia
🇮🇪	flag-ie ireland
🇮🇱	flag-il israel
🇮🇲	flag-im isle_of_man
🇮🇳	flag-in india
🇮🇴	flag-io british_indian_ocean_territory
🇮🇶	flag-iq iraq
🇮🇷	flag-ir iran
🇮🇸	flag-is iceland
🇮🇹	it flag-it
🇯🇪	flag-je jersey
🇯🇲	flag-jm jamaica
🇯🇴	flag-jo jordan
🇯🇵	jp flag-jp
🇰🇪	flag-ke kenya
🇰🇬	flag-kg kyrgyzstan
🇰🇭	flag-kh cambodia
🇰🇮	flag-ki kiribati
🇰🇲	flag-km comoros
🇰🇳	flag-kn st_kitts_nevis
🇰🇵	flag-kp north_korea
🇰🇷	kr flag-kr
🇰🇼	flag-kw kuwait
🇰🇾	flag-ky cayman_islands
🇰🇿	flag-kz kazakhstan
🇱🇦	flag-la laos
🇱🇧	flag-lb lebanon
🇱🇨	flag-lc st_lucia
🇱🇮	flag-li liechtenstein
🇱🇰	flag-lk sri_lanka
🇱🇷	flag-lr liberia
🇱🇸	flag-ls lesotho
🇱🇹	flag-lt lithuania
🇱🇺	flag-lu luxembourg
🇱🇻	flag-lv latvia
🇱🇾	flag-ly libya
🇲🇦	flag-ma morocco
🇲🇨	flag-mc monaco
🇲🇩	flag-md moldova
🇲🇪	flag-me montenegro
🇲🇫	flag-mf
🇲🇬	flag-mg madagascar
🇲🇭	flag-mh marshall_islands
🇲🇰	flag-mk macedonia
🇲🇱	flag-ml mali
🇲🇲	flag-mm myanmar
🇲🇳	flag-mn mongolia
🇲🇴	flag-mo macau
🇲🇵	flag-mp northern_mariana_islands
🇲🇶	flag-mq martinique
🇲🇷	flag-mr mauritania
🇲🇸	flag-ms montserrat
🇲🇹	flag-mt malta
🇲🇺	flag-mu mauritius
🇲🇻	flag-mv maldives
🇲🇼	flag-mw malawi
🇲🇽	flag-mx mexico
🇲🇾	flag-my malaysia
🇲🇿	flag-mz mozambique
🇳🇦	flag-na namibia
🇳🇨	flag-nc new_caledonia
🇳🇪	flag-ne niger
🇳🇫	flag-nf norfolk_island
🇳🇬	flag-ng nigeria
🇳🇮	flag-ni nicaragua
🇳🇱	flag-nl netherlands
🇳🇴	flag-no norway
🇳🇵	flag-np nepal
🇳🇷	flag-nr nauru
🇳🇺	flag-nu niue
🇳🇿	flag-nz new_zealand
🇴🇲	flag-om oman
🇵🇦	flag-pa panama
🇵🇪	flag-pe peru
🇵🇫	flag-pf french_polynesia
🇵🇬	flag-pg papua_new_guinea
🇵🇭	flag-ph philippines
🇵🇰	flag-pk pakistan pk
🇵🇱	flag-pl poland
🇵🇲	flag-pm st_pierre_miquelon
🇵🇳	flag-pn pitcairn_islands
🇵🇷	flag-pr puerto_rico
🇵🇸	flag-ps palestinian_territories
🇵🇹	flag-pt portugal
🇵🇼	flag-pw palau
🇵🇾	flag-py paraguay
🇶🇦	flag-qa qatar
🇷🇪	flag-re reunion
🇷🇴	flag-ro romania
🇷🇸	flag-rs serbia
🇷🇺	ru flag-ru
🇷🇼	flag-rw rwanda
🇸🇦	flag-sa saudi_arabia
🇸🇧	flag-sb solomon_islands
🇸🇨	flag-sc seychelles
🇸🇩	flag-sd sudan
🇸🇪	flag-se sweden
🇸🇬	flag-sg singapore
🇸🇭	flag-sh st_helena
🇸🇮	flag-si slovenia
🇸🇯	flag-sj
🇸🇰	flag-sk slovakia
🇸🇱	flag-sl sierra_leone
🇸🇲	flag-sm san_marino
🇸🇳	flag-sn senegal
🇸🇴	flag-so somalia
🇸🇷	flag-sr suriname
🇸🇸	flag-ss south_sudan
🇸🇹	flag-st sao_tome_principe
🇸🇻	flag-sv el_salvador
🇸🇽	flag-sx sint_maarten
🇸🇾	flag-sy syria
🇸🇿	flag-sz swaziland
🇹🇦	flag-ta
🇹🇨	flag-tc turks_caicos_islands
🇹🇩	flag-td chad
🇹🇫	flag-tf french_southern_territories
🇹🇬	flag-tg togo
🇹🇭	flag-th thailand
🇹🇯	flag-tj tajikistan
🇹🇰	flag-tk tokelau
🇹🇱	flag-tl timor_leste
🇹🇲	flag-tm turkmenistan
🇹🇳	flag-tn tunisia
🇹🇴	flag-to tonga
🇹🇷	flag-tr tr
🇹🇹	flag-tt trinidad_tobago
🇹🇻	flag-tv tuvalu
🇹🇼	flag-tw taiwan
🇹🇿	flag-tz tanzania
🇺🇦	flag-ua ukraine
🇺🇬	flag-ug uganda
🇺🇲	flag-um
🇺🇳	flag-un
🇺🇸	us flag-us
🇺🇾	flag-uy uruguay
🇺🇿	flag-uz uzbekistan
🇻🇦	flag-va vatican_city
🇻🇨	flag-vc st_vincent_grenadines
🇻🇪	flag-ve venezuela
🇻🇬	flag-vg british_virgin_islands
🇻🇮	flag-vi us_virgin_islands
🇻🇳	flag-vn vietnam
🇻🇺	flag-vu vanuatu
🇼🇫	flag-wf wallis_futuna
🇼🇸	flag-ws samoa
🇽🇰	flag-xk kosovo
🇾🇪	flag-ye yemen
🇾🇹	flag-yt mayotte
🇿🇦	flag-za south_africa za
🇿🇲	flag-zm zambia
🇿🇼	flag-zw zimbabwe
🏴󠁧󠁢󠁥󠁮󠁧󠁿	flag-england
🏴󠁧󠁢󠁳󠁣󠁴󠁿	flag-scotland
🏴󠁧󠁢󠁷󠁬󠁳󠁿	flag-wales
@component
🏻	skin-tone-2
🏼	skin-tone-3
🏽	skin-tone-4
🏾	skin-tone-5
🏿	skin-tone-6
"""#
}
